.nh
.TH "GH-CODESPACE" "1" "Jul 2025" "" "GitHub CLI manual"

.SH NAME
gh-codespace - Connect to and manage codespaces

.SH SYNOPSIS
\fBgh codespace [flags]\fR

.SH COMMANDS
.TP
\fBgh-codespace-cp(1)\fR
Copy files between codespace and local file system

.SH OPTIONS
.TP
\fB-c\fR, \fB--codespace\fR \fI<name>\fR
Name of the codespace
