use crate::{Arg, Command};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum HelpFormat {
    /// Output generated by clap (Rust).
    Clap,
    /// Output generated by Python's argparse module.
    Argparse,
    /// Unknown or generic format.
    Generic,
}

fn detect_format(help: &str) -> HelpFormat {
    // clap outputs a "Usage:" line (capital U) and uses long option descriptions
    // indented underneath the flag, separated by an empty line.
    let has_usage = help.contains("Usage:");
    let has_commands_section = help.contains("\nCommands:\n") || help.contains("\nSubcommands:\n");
    // argparse always prints "usage:" (lowercase) and "optional arguments:" or
    // "options:" sections.
    let has_positional = help.lines().any(|l| {
        let t = l.trim();
        t == "positional arguments:" || t == "arguments:"
    });
    let has_optional = help.lines().any(|l| {
        let t = l.trim();
        t == "optional arguments:" || t == "options:" || t.starts_with("named arguments:")
    });

    if has_positional || (has_optional && !has_commands_section) {
        // Pure argparse output never has a "Commands:" section.
        HelpFormat::Argparse
    } else if has_usage || has_commands_section {
        HelpFormat::Clap
    } else {
        HelpFormat::Generic
    }
}

/// Parse a `--help` string into a [`Command`] with the best fidelity possible.
///
/// The function auto-detects whether the string was produced by clap,
/// Python argparse, or an unknown tool, and dispatches accordingly.
pub fn parse_help(help: &str) -> Command {
    let mut cmd = match detect_format(help) {
        HelpFormat::Clap => parse_help_clap(help),
        HelpFormat::Argparse => parse_help_argparse(help),
        HelpFormat::Generic => parse_help_generic(help),
    };
    // Expand bracketed negation flags (like --[no-]color) into both variants
    cmd.expand_no_options();
    cmd
}

/// Leading-space count for a line (tabs count as 1).
fn indent_of(line: &str) -> usize {
    line.chars().take_while(|c| *c == ' ' || *c == '\t').count()
}

/// Try to parse a flag token like `-v`, `--verbose`, or `--output <FILE>`.
/// Returns `(short, long, value_type)`.
#[cfg_attr(not(test), allow(dead_code))]
pub(crate) fn parse_flag_tokens(token: &str) -> (Option<String>, Option<String>, Option<String>) {
    // Split on commas / whitespace to handle "-v, --verbose <FILE>"
    let mut short = None;
    let mut long = None;
    let mut value_type = None;

    // Tokenise: split on ", " first, then whitespace
    let pieces: Vec<&str> = token.split_whitespace().collect();
    for piece in &pieces {
        if piece.starts_with("--") {
            // May be "--flag" or "--flag=<VAL>"
            if let Some((flag, val)) = piece.split_once('=') {
                long = Some(flag.trim_end_matches(',').to_string());
                value_type = Some(val.trim_matches(|c| c == '<' || c == '>').to_string());
            } else {
                long = Some(piece.trim_end_matches(',').to_string());
            }
        } else if let Some(short_candidate) = piece.strip_prefix('-') {
            let short_candidate = short_candidate.trim_end_matches(',');
            // Only treat single-character forms like `-v` as clap short flags.
            // Multi-character forms such as `-wk`, `-wK`, or `-U[dlexhi]` are
            // command-specific syntax, not plain one-letter short options.
            // We also allow forms ending with '#' (like `-T#` or `-b#`).
            let count = short_candidate.chars().count();
            if count == 1 || (count == 2 && short_candidate.ends_with('#')) {
                short = Some(format!("-{short_candidate}"));
            }
        } else if piece.starts_with('<') || piece.starts_with('[') {
            // Meta-variable — only capture the first one found so that description
            // text like `[default: 10]` does not overwrite an already-parsed hint.
            // Subsequent bracketed tokens (e.g. `[boolean]`, `[default: …]`) are
            // intentionally ignored once a value-type has been established.
            if value_type.is_none() {
                value_type = Some(
                    piece
                        .trim_matches(|c| c == '<' || c == '>' || c == '[' || c == ']')
                        .to_string(),
                );
            }
        } else if value_type.is_none()
            && !piece.is_empty()
            && (piece.chars().all(|c| {
                c.is_uppercase()
                    || c == '_'
                    || c == '-'
                    || c == '#'
                    || c == '|'
                    || c == '{'
                    || c == '}'
            }))
        {
            let clean = piece.trim_end_matches(',');
            value_type = Some(clean.to_string());
        }
    }
    (short, long, value_type)
}

/// Collect continuation lines: lines whose indent > `base_indent` (or blank).
/// Returns the combined description string.
fn collect_continuation<'a>(
    lines: &'a [&'a str],
    start: usize,
    base_indent: usize,
) -> (String, usize) {
    let mut desc_parts = Vec::new();
    let mut i = start;
    while i < lines.len() {
        let line = lines[i];
        if line.trim().is_empty() {
            // blank line ends the block
            break;
        }
        let ind = indent_of(line);
        if ind <= base_indent {
            break;
        }
        // A deeper-indented line that starts with `-` is another flag entry,
        // not description text. This handles tools like cargo that mix indent
        // levels within a single Options section.
        if line.trim().starts_with('-') {
            break;
        }
        desc_parts.push(line.trim().to_string());
        i += 1;
    }
    (desc_parts.join(" "), i)
}

/// Parse clap-style `--help` output.
pub fn parse_help_clap(help: &str) -> Command {
    let lines: Vec<&str> = help.lines().collect();
    let mut cmd = Command::default();

    if let Some(usage_pos) = lines
        .iter()
        .position(|l| l.trim_start().starts_with("Usage:"))
    {
        let after = lines[usage_pos].trim_start_matches(|c: char| c.is_whitespace());
        let after = after.strip_prefix("Usage:").unwrap_or(after).trim();
        if let Some(name_part) = after.split_whitespace().next() {
            cmd.name = Some(name_part.to_string());
        } else {
            for next_line in &lines[usage_pos + 1..] {
                let t = next_line.trim();
                if !t.is_empty() {
                    if let Some(name_part) = t.split_whitespace().next() {
                        cmd.name = Some(name_part.to_string());
                    }
                    break;
                }
            }
        }
    }

    let usage_pos = lines
        .iter()
        .position(|l| l.trim_start().starts_with("Usage:"))
        .unwrap_or(0);
    for line in &lines[..usage_pos] {
        let t = line.trim();
        if !t.is_empty() {
            let is_header = t.starts_with("***")
                || t.contains(" version ")
                || t.contains(" v1.")
                || t.contains(" v2.")
                || t.contains(" v0.")
                || t.contains("by ")
                || t.contains("Copyright");
            if !is_header {
                cmd.description = Some(t.to_string());
                break;
            }
        }
    }

    let mut i = 0;
    while i < lines.len() {
        let trimmed = lines[i].trim();

        if trimmed == "Commands:" || trimmed == "Subcommands:" || trimmed == "Available Commands:" {
            i += 1;
            while i < lines.len() {
                let line = lines[i];
                if line.trim().is_empty() {
                    i += 1;
                    break;
                }
                if indent_of(line) == 0 && !line.trim().is_empty() {
                    break;
                }
                let trimmed_line = line.trim();
                let mut parts = trimmed_line.splitn(2, "  ");
                let sub_name = parts.next().unwrap_or("").trim().to_string();
                let sub_desc = parts.next().map(|s| s.trim().to_string());
                if !sub_name.is_empty() {
                    cmd.subcommands.push(Command {
                        name: Some(sub_name),
                        description: sub_desc,
                        ..Command::default()
                    });
                }
                i += 1;
            }
            continue;
        }

        let is_options_section = trimmed.ends_with(':') && {
            let lower = trimmed.to_lowercase();
            lower.contains("options")
                || lower.contains("flags")
                || lower.contains("arguments")
                || lower.contains("args")
                || lower.contains("builder")
                || lower.contains("parameters")
                || lower.contains("settings")
        };

        if is_options_section {
            i += 1;
            while i < lines.len() {
                let line = lines[i];
                if line.trim().is_empty() {
                    i += 1;
                    continue;
                }
                if indent_of(line) == 0 {
                    break;
                }
                let flag_indent = indent_of(line);
                let flag_part = line.trim();

                if !flag_part.starts_with('-') && !flag_part.starts_with('[') {
                    i += 1;
                    continue;
                }

                let token_part = flag_part
                    .find("  ")
                    .map(|pos| &flag_part[..pos])
                    .unwrap_or(flag_part);
                let (short, long, value_type) = parse_flag_tokens(token_part);

                let inline_desc: Option<String> = flag_part.find("  ").and_then(|pos| {
                    let d = flag_part[pos..].trim();
                    if d.is_empty() {
                        None
                    } else {
                        Some(d.to_string())
                    }
                });
                let (cont_desc, next_i) = collect_continuation(&lines, i + 1, flag_indent);
                i = next_i;

                let description = match (inline_desc, cont_desc.as_str()) {
                    (Some(d), "") => Some(d),
                    (None, d) if !d.is_empty() => Some(d.to_string()),
                    (Some(d), rest) => Some(format!("{} {}", d, rest)),
                    (None, _) => None,
                };

                let num_args = if value_type.is_some() {
                    Some("1".to_string())
                } else {
                    None
                };

                cmd.args.push(Arg {
                    short,
                    long,
                    description,
                    value_type,
                    num_args,
                });
            }
            continue;
        }

        i += 1;
    }

    cmd
}

/// Parse Python argparse-style `--help` output.
pub fn parse_help_argparse(help: &str) -> Command {
    let lines: Vec<&str> = help.lines().collect();
    let mut cmd = Command::default();

    if let Some(usage_line) = lines
        .iter()
        .find(|l| l.trim_start().to_lowercase().starts_with("usage:"))
    {
        let after = usage_line
            .trim_start_matches(|c: char| c.is_whitespace())
            .to_lowercase();
        let after = after.strip_prefix("usage:").unwrap_or(&after).trim();
        if let Some(name) = after.split_whitespace().next() {
            cmd.name = Some(name.to_string());
        }
    }

    let usage_pos = lines
        .iter()
        .position(|l| l.trim_start().to_lowercase().starts_with("usage:"))
        .unwrap_or(0);
    let mut found_blank = false;
    for line in &lines[usage_pos + 1..] {
        if line.trim().is_empty() {
            found_blank = true;
        } else if found_blank {
            let t = line.trim();
            if !t.ends_with(':') {
                cmd.description = Some(t.to_string());
            }
            break;
        }
    }

    let mut i = 0;
    while i < lines.len() {
        let trimmed = lines[i].trim();

        let is_args_section = trimmed == "positional arguments:"
            || trimmed == "optional arguments:"
            || trimmed == "options:"
            || trimmed.starts_with("named arguments:");

        if is_args_section {
            i += 1;
            while i < lines.len() {
                let line = lines[i];
                if line.trim().is_empty() {
                    i += 1;
                    break;
                }
                if indent_of(line) == 0 && line.trim().ends_with(':') {
                    break;
                }
                let flag_indent = indent_of(line);
                let flag_part = line.trim();

                let (short, long, value_type) = if flag_part.starts_with('-') {
                    let token_part = flag_part
                        .find("  ")
                        .map(|pos| &flag_part[..pos])
                        .unwrap_or(flag_part);
                    parse_flag_tokens(token_part)
                } else {
                    let name_token = flag_part.split_whitespace().next().unwrap_or("");
                    (None, Some(name_token.to_string()), None)
                };

                let inline_desc: Option<String> = if let Some(pos) = flag_part.find("  ") {
                    let d = flag_part[pos..].trim();
                    if !d.is_empty() {
                        Some(d.to_string())
                    } else {
                        None
                    }
                } else {
                    None
                };

                let (cont_desc, next_i) = collect_continuation(&lines, i + 1, flag_indent);
                i = next_i;

                let description = match (inline_desc, cont_desc.as_str()) {
                    (Some(d), "") => Some(d),
                    (None, d) if !d.is_empty() => Some(d.to_string()),
                    (Some(d), rest) => Some(format!("{} {}", d, rest)),
                    (None, _) => None,
                };

                let num_args = if value_type.is_some() {
                    Some("1".to_string())
                } else {
                    None
                };

                cmd.args.push(Arg {
                    short,
                    long,
                    description,
                    value_type,
                    num_args,
                });
            }
            continue;
        }

        i += 1;
    }

    cmd
}

/// Fallback parser for unrecognised help formats.
pub fn parse_help_generic(help: &str) -> Command {
    let lines: Vec<&str> = help.lines().collect();
    let mut cmd = Command::default();

    for line in &lines {
        let lower = line.trim().to_lowercase();
        if lower.starts_with("usage:") {
            let after = line
                .trim()
                .trim_start_matches(|c: char| c.is_alphabetic() || c == ':')
                .trim();
            if let Some(name) = after.split_whitespace().next() {
                cmd.name = Some(name.to_string());
                break;
            }
        }
    }

    for line in &lines {
        let t = line.trim();
        if !t.is_empty() && !t.starts_with('-') && !t.to_lowercase().starts_with("usage:") {
            cmd.description = Some(t.to_string());
            break;
        }
    }

    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        let flag_part = line.trim();

        if flag_part.starts_with('-') {
            let flag_indent = indent_of(line);
            let token_part = flag_part
                .find("  ")
                .map(|pos| &flag_part[..pos])
                .unwrap_or(flag_part);
            let (short, long, value_type) = parse_flag_tokens(token_part);

            let inline_desc: Option<String> = if let Some(pos) = flag_part.find("  ") {
                let d = flag_part[pos..].trim();
                if !d.is_empty() {
                    Some(d.to_string())
                } else {
                    None
                }
            } else {
                None
            };

            let (cont_desc, next_i) = collect_continuation(&lines, i + 1, flag_indent);
            i = next_i;

            let description = match (inline_desc, cont_desc.as_str()) {
                (Some(d), "") => Some(d),
                (None, d) if !d.is_empty() => Some(d.to_string()),
                (Some(d), rest) => Some(format!("{} {}", d, rest)),
                (None, _) => None,
            };

            let num_args = if value_type.is_some() {
                Some("1".to_string())
            } else {
                None
            };

            cmd.args.push(Arg {
                short,
                long,
                description,
                value_type,
                num_args,
            });
            continue;
        }

        i += 1;
    }

    cmd
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{SynthesisStrategy, synthesize_completion};

    fn long_names(cmd: &Command) -> Vec<&str> {
        cmd.args.iter().filter_map(|a| a.long.as_deref()).collect()
    }

    fn short_names(cmd: &Command) -> Vec<&str> {
        cmd.args.iter().filter_map(|a| a.short.as_deref()).collect()
    }

    fn subcommand_names(cmd: &Command) -> Vec<&str> {
        cmd.subcommands
            .iter()
            .filter_map(|s| s.name.as_deref())
            .collect()
    }

    fn arg_by_long<'a>(cmd: &'a Command, long: &str) -> Option<&'a Arg> {
        cmd.args.iter().find(|a| a.long.as_deref() == Some(long))
    }

    fn subcommand_by_name<'a>(cmd: &'a Command, name: &str) -> Option<&'a Command> {
        cmd.subcommands
            .iter()
            .find(|s| s.name.as_deref() == Some(name))
    }

    const FLYLINE_HELP: &str = r#"Usage: flyline [OPTIONS] [COMMAND]

Commands:
  set-agent-mode        Configure AI agent mode.
  create-prompt-widget  Create a custom prompt widget.
  set-style             Configure the colour palette.
  set-cursor            Configure the cursor appearance and animation.
  key                   Manage keybindings.
  dump-logs             Dump in-memory logs to file.
  stream-logs           Dump current logs to PATH and append new logs.
  run-tutorial          Run the interactive tutorial for first-time users.
  help                  Print this message or the help of the given subcommand(s)

Options:
      --version
          Show version information

      --log-level <LEVEL>
          Set the logging level
          
          [possible values: error, warn, info, debug, trace]

      --load-zsh-history [<PATH>]
          Load Zsh history in addition to Bash history. Optionally specify a PATH to the Zsh history file; if omitted, defaults to $HOME/.zsh_history

      --show-animations [<SHOW_ANIMATIONS>]
          Show animations
          
          [possible values: true, false]

      --show-inline-history [<SHOW_INLINE_HISTORY>]
          Show inline history suggestions
          
          [possible values: true, false]

      --auto-close-chars [<AUTO_CLOSE_CHARS>]
          Enable automatic closing character insertion (e.g. insert `)` after `(`)
          
          [possible values: true, false]

      --matrix-animation [<MATRIX_ANIMATION>]
          Run matrix animation in the terminal background. Use `on` to always show it, `off` to disable it, or an integer number of seconds to show it after that many seconds of inactivity (no keypress or mouse event). Defaults to `off`; passing the flag without a value is equivalent to `on`

      --set-frame-rate <FPS>
          Render frame rate in frames per second (1–120, default 24)

      --set-mouse-mode <MODE>
          Mouse capture mode (disabled, simple, smart). Default is smart.

      --send-shell-integration-codes [<SEND_SHELL_INTEGRATION_CODES>]
          Send shell integration escape codes (OSC 133 / OSC 633): none, only-prompt-pos, or full

      --enable-extended-key-codes [<ENABLE_EXTENDED_KEY_CODES>]
          Whether to request the use of extended (kitty-protocol) keyboard codes during startup. Enabled by default; pass `--enable-extended-key-codes false` (or with no value) to disable it on terminals that misbehave when the request is sent
          
          [possible values: true, false]

  -h, --help
          Print help (see a summary with '-h')

Read more at https://github.com/HalFrgrd/flyline
"#;

    #[test]
    fn test_flyline_help_clap() {
        let cmd = parse_help(FLYLINE_HELP);
        assert_eq!(cmd.name.as_deref(), Some("flyline"));

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"set-agent-mode"));
        assert!(subs.contains(&"create-prompt-widget"));
        assert!(subs.contains(&"set-style"));
        assert!(subs.contains(&"key"));
        assert!(subs.contains(&"dump-logs"));
        assert!(subs.contains(&"stream-logs"));
        assert!(subs.contains(&"run-tutorial"));
        assert_eq!(
            subcommand_by_name(&cmd, "set-agent-mode").and_then(|s| s.description.as_deref()),
            Some("Configure AI agent mode.")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "dump-logs").and_then(|s| s.description.as_deref()),
            Some("Dump in-memory logs to file.")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "stream-logs").and_then(|s| s.description.as_deref()),
            Some("Dump current logs to PATH and append new logs.")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "run-tutorial").and_then(|s| s.description.as_deref()),
            Some("Run the interactive tutorial for first-time users.")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--version"));
        assert!(!longs.contains(&"--dump-logs"));
        assert!(!longs.contains(&"--stream-logs"));
        assert!(!longs.contains(&"--run-tutorial"));
        assert!(longs.contains(&"--log-level"));
        assert!(longs.contains(&"--set-frame-rate"));
        assert!(longs.contains(&"--set-mouse-mode"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        assert_eq!(
            arg_by_long(&cmd, "--log-level").and_then(|a| a.value_type.as_deref()),
            Some("LEVEL")
        );
        assert_eq!(
            arg_by_long(&cmd, "--set-frame-rate").and_then(|a| a.value_type.as_deref()),
            Some("FPS")
        );
        assert_eq!(
            arg_by_long(&cmd, "--set-mouse-mode").and_then(|a| a.value_type.as_deref()),
            Some("MODE")
        );

        assert_eq!(
            arg_by_long(&cmd, "--version").and_then(|a| a.description.as_deref()),
            Some("Show version information")
        );
        assert!(
            arg_by_long(&cmd, "--log-level")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("logging level")
        );
    }

    const FLYLINE_CREATE_ANIM_HELP: &str = r#"Create a custom prompt animation.

Instances of NAME in prompt strings (PS1, RPS1, PS1_FILL) are replaced
with the current animation frame on every render.  Frames may include
ANSI colour sequences written as `\e` (e.g. `\e[33m`).

Examples:
  flyline create-anim --name "MY_ANIMATION" --fps 10  ⣾ ⣷ ⣯ ⣟ ⡿ ⢿ ⣻ ⣽
  flyline create-anim --name "john" --ping-pong --fps 5  '\e[33m\u' '\e[31m\u' '\e[35m\u' '\e[36m\u'

Usage: flyline create-anim [OPTIONS] --name <NAME> [FRAMES]...

Arguments:
  [FRAMES]...
          One or more animation frames (positional).  Use `\e` for the ESC character

Options:
      --name <NAME>
          Name to embed in prompt strings as the animation placeholder

      --fps <FPS>
          Playback speed in frames per second (default: 10)
          
          [default: 10]

      --ping-pong
          Reverse direction at each end instead of wrapping (ping-pong / bounce mode)

  -h, --help
          Print help (see a summary with '-h')
"#;

    #[test]
    fn test_flyline_create_anim_help_clap() {
        let cmd = parse_help(FLYLINE_CREATE_ANIM_HELP);
        assert_eq!(cmd.name.as_deref(), Some("flyline"));
        assert!(
            cmd.description
                .as_deref()
                .unwrap_or("")
                .contains("animation")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--name"));
        assert!(longs.contains(&"--fps"));
        assert!(longs.contains(&"--ping-pong"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        assert_eq!(
            arg_by_long(&cmd, "--name").and_then(|a| a.value_type.as_deref()),
            Some("NAME")
        );
        assert_eq!(
            arg_by_long(&cmd, "--fps").and_then(|a| a.value_type.as_deref()),
            Some("FPS")
        );

        assert!(
            arg_by_long(&cmd, "--name")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("animation placeholder")
        );
        assert!(
            arg_by_long(&cmd, "--fps")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("frames per second")
        );
        assert!(
            arg_by_long(&cmd, "--ping-pong")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("Reverse direction")
        );
    }

    const CARGO_HELP: &str = r#"Rust's package manager

Usage: cargo [+toolchain] [OPTIONS] [COMMAND]
       cargo [+toolchain] [OPTIONS] -Zscript [ARGS]...

Options:
  -V, --version              Print version info and exit
      --list                 List installed commands
      --explain <CODE>       Run `rustc --explain CODE`
  -v, --verbose              Use verbose output (-vv very verbose/build.rs output)
  -q, --quiet                Do not print cargo log messages
      --color <WHEN>         Coloring: auto, always, never
  -C <DIRECTORY>             Change to DIRECTORY before doing anything (nightly-only)
      --frozen               Require Cargo.lock and cache are up to date
      --locked               Require Cargo.lock is up to date
      --offline              Run without accessing the network
      --config <KEY=VALUE>   Override a configuration value
  -Z <FLAG>                  Unstable (nightly-only) flags to Cargo, see 'cargo -Z help' for details
  -h, --help                 Print help

Some common cargo commands are (see all commands with --list):
    build, b    Compile the current package
    check, c    Analyze the current package and report errors, but don't build object files
    clean       Remove the generated artifacts
    doc, d      Build this package's and its dependencies' documentation
    run, r      Run a binary or example of the local package
    test, t     Run the tests
    bench       Run the benchmarks
    update      Update dependencies listed in Cargo.lock
    search      Search registry for crates
    publish     Publish this package to the registry
    add         Add dependencies to a manifest file
    remove      Remove dependencies from a manifest file

See 'cargo help <command>' for more information on a specific command.
"#;

    #[test]
    fn test_cargo_help_clap() {
        let cmd = parse_help(CARGO_HELP);
        assert_eq!(cmd.name.as_deref(), Some("cargo"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--verbose"));
        assert!(longs.contains(&"--quiet"));
        assert!(longs.contains(&"--explain"));
        assert!(longs.contains(&"--color"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-V"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-h"));

        assert_eq!(
            arg_by_long(&cmd, "--explain").and_then(|a| a.value_type.as_deref()),
            Some("CODE")
        );
        assert_eq!(
            arg_by_long(&cmd, "--color").and_then(|a| a.value_type.as_deref()),
            Some("WHEN")
        );
    }

    const PYTHON_HELP: &str = r#"usage: python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Options and arguments (and corresponding environment variables):
-b     : issue warnings about str(bytes_instance), str(bytearray_instance)
         and comparing bytes/bytearray with str. (-bb: issue errors)
-B     : don't write .pyc files on import; also PYTHONDONTWRITEBYTECODE=x
-c cmd : program passed in as string (terminates option list)
-d     : debug output from parser; also PYTHONDEBUG=x
-E     : ignore PYTHON* environment variables (such as PYTHONPATH)
-h     : print this help message and exit (also --help)
-i     : inspect interactively after running script; forces a prompt even
         if stdin does not appear to be a terminal; also PYTHONINSPECT=x
-I     : isolate Python from the user's environment (implies -E and -s)
-m mod : run library module as a script (terminates option list)
-O     : remove assert and __debug__-dependent statements; add .opt-1 before
         .pyc extension; also PYTHONOPTIMIZE=x
-OO    : do -O changes and also discard docstrings; add .opt-2 before
         .pyc extension
-q     : don't print version and copyright messages on interactive startup
-s     : don't add user site directory to sys.path; also PYTHONNOUSERSITE=x
-S     : don't imply 'import site' on initialization
-u     : force the stdout and stderr streams to be unbuffered;
         this option has no effect on stdin; also PYTHONASYNCIOGENIGNORE=x
-v     : verbose (trace import statements); also PYTHONVERBOSE=x;
         can be supplied multiple times to increase verbosity
-V     : print the Python version number and exit (also --version)
         --version :  print just the version number to stdout and exit
-W arg : warning control; arg is action:message:category:module:lineno
         also PYTHONWARNINGS=x
-x     : skip first line of source, allowing use of non-Unix forms of #!cmd
-X opt : set implementation-specific option
--check-hash-based-pycs always|default|never:
    control how Python invalidates hash-based .pyc files
file   : program read from script file
-      : program read from stdin (default; interactive mode if a tty)
arg ...: arguments passed to program in sys.argv[1:]

Other environment variables:
PYTHONSTARTUP: file executed on interactive startup (no default)
PYTHONPATH   : ':'-separated list of directories prefixed to the
               default module search path.  The result is sys.path.
"#;

    #[test]
    fn test_python_help_generic() {
        let cmd = parse_help(PYTHON_HELP);
        assert_eq!(cmd.name.as_deref(), Some("python3"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-V"));
        assert!(shorts.contains(&"-q"));

        assert!(
            cmd.args
                .iter()
                .find(|a| a.short.as_deref() == Some("-h"))
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("help message")
        );
    }

    const ARGPARSE_EXAMPLE: &str = r#"usage: prog.py [-h] [--foo FOO] bar

A sample argparse program.

positional arguments:
  bar          the bar argument

optional arguments:
  -h, --help   show this help message and exit
  --foo FOO    the foo value
"#;

    #[test]
    fn test_argparse_example() {
        let cmd = parse_help(ARGPARSE_EXAMPLE);
        assert_eq!(cmd.name.as_deref(), Some("prog.py"));
        assert!(
            cmd.description
                .as_deref()
                .unwrap_or("")
                .contains("argparse")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"bar"));
        assert!(longs.contains(&"--foo"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        assert!(
            arg_by_long(&cmd, "bar")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("bar argument")
        );
        assert!(
            arg_by_long(&cmd, "--foo")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("foo value")
        );
    }

    const ARGPARSE_SUBPARSERS: &str = r#"usage: myapp [-h] {init,run,stop} ...

My Application

positional arguments:
  {init,run,stop}
    init           Initialize the project
    run            Run the application
    stop           Stop the application

optional arguments:
  -h, --help       show this help message and exit
  --verbose        Enable verbose output
"#;

    #[test]
    fn test_argparse_subparsers() {
        let cmd = parse_help(ARGPARSE_SUBPARSERS);
        assert_eq!(cmd.name.as_deref(), Some("myapp"));
        assert!(cmd.description.as_deref().unwrap_or("").contains("My"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--verbose"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        assert!(
            arg_by_long(&cmd, "--verbose")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("verbose output")
        );
    }

    const CLICK_HELP: &str = r#"Usage: cli [OPTIONS] COMMAND [ARGS]...

  A simple CLI built with Click.

Options:
  --name TEXT      The person to greet.
  --count INTEGER  Number of greetings.  [default: 1]
  -v, --verbose    Enable verbose output.
  --help           Show this message and exit.

Commands:
  hello    Greet someone.
  goodbye  Say goodbye.
"#;

    #[test]
    fn test_click_help() {
        let cmd = parse_help(CLICK_HELP);
        assert_eq!(cmd.name.as_deref(), Some("cli"));

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"hello"));
        assert!(subs.contains(&"goodbye"));
        assert_eq!(
            subcommand_by_name(&cmd, "hello").and_then(|s| s.description.as_deref()),
            Some("Greet someone.")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "goodbye").and_then(|s| s.description.as_deref()),
            Some("Say goodbye.")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--name"));
        assert!(longs.contains(&"--count"));
        assert!(longs.contains(&"--verbose"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-v"));
    }

    const ARGH_HELP: &str = r#"usage: myapp [-h] [--verbose] name

A program using argh.

positional arguments:
  name         the name argument

optional arguments:
  -h, --help   show this help message and exit
  --verbose    enable verbose output
"#;

    #[test]
    fn test_argh_help() {
        let cmd = parse_help(ARGH_HELP);
        assert_eq!(cmd.name.as_deref(), Some("myapp"));
        assert!(cmd.description.as_deref().unwrap_or("").contains("argh"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"name"));
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--verbose"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        assert!(
            arg_by_long(&cmd, "name")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("name argument")
        );
        assert!(
            arg_by_long(&cmd, "--verbose")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("verbose output")
        );
    }

    const YARGS_HELP: &str = r#"my-cli [options]

Commands:
  serve  Start the development server
  build  Build the project for production
  test   Run the test suite

Options:
      --help     Show help                 [boolean]
      --version  Show version number       [boolean]
  -p, --port     Port to listen on         [number]
"#;

    #[test]
    fn test_yargs_help() {
        let cmd = parse_help(YARGS_HELP);
        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"serve"));
        assert!(subs.contains(&"build"));
        assert!(subs.contains(&"test"));

        assert!(
            subcommand_by_name(&cmd, "serve")
                .and_then(|s| s.description.as_deref())
                .unwrap_or("")
                .contains("development server")
        );
        assert!(
            subcommand_by_name(&cmd, "build")
                .and_then(|s| s.description.as_deref())
                .unwrap_or("")
                .contains("production")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--port"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-p"));
    }

    const COMMANDER_HELP: &str = r#"Usage: program [options] [command]

Options:
  -V, --version  output the version number
  -h, --help     display help for command

Commands:
  start          Start the server
  stop           Stop the server
  status         Show the server status
"#;

    #[test]
    fn test_commander_help() {
        let cmd = parse_help(COMMANDER_HELP);
        assert_eq!(cmd.name.as_deref(), Some("program"));

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"start"));
        assert!(subs.contains(&"stop"));
        assert!(subs.contains(&"status"));
        assert_eq!(
            subcommand_by_name(&cmd, "start").and_then(|s| s.description.as_deref()),
            Some("Start the server")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "stop").and_then(|s| s.description.as_deref()),
            Some("Stop the server")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-V"));
        assert!(shorts.contains(&"-h"));
    }

    const COBRA_HELP: &str = r#"A brief description of your application.

Usage:
  myapp [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  serve       Start the server
  version     Print the version number

Flags:
  -h, --help     help for myapp
  -t, --toggle   Help message for toggle

Global Flags:
      --config string      config file (default "$HOME/.myapp.yaml")
      --log-level string   Log level (default "info")

Use "myapp [command] --help" for more information about a command.
"#;

    #[test]
    fn test_cobra_help() {
        let cmd = parse_help(COBRA_HELP);
        assert_eq!(cmd.name.as_deref(), Some("myapp"));
        assert!(
            cmd.description
                .as_deref()
                .unwrap_or("")
                .contains("application")
        );

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"serve"));
        assert!(subs.contains(&"version"));
        assert_eq!(
            subcommand_by_name(&cmd, "serve").and_then(|s| s.description.as_deref()),
            Some("Start the server")
        );
        assert!(
            subcommand_by_name(&cmd, "completion")
                .and_then(|s| s.description.as_deref())
                .unwrap_or("")
                .contains("autocompletion")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--toggle"));
        assert!(longs.contains(&"--config"));
        assert!(longs.contains(&"--log-level"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));
        assert!(shorts.contains(&"-t"));
    }

    const DOCOPT_HELP: &str = r#"Usage:
  naval_fate ship <name> move <x> <y> [--speed=<kn>]
  naval_fate ship shoot <x> <y>
  naval_fate mine (set|remove) <x> <y> [--moored|--drifting]
  naval_fate (-h | --help)
  naval_fate --version

Options:
  -h --help     Show this screen.
  --version     Show version.
  --speed=<kn>  Speed in knots [default: 10].
  --moored      Moored (anchored) mine.
  --drifting    Drifting mine.
"#;

    #[test]
    fn test_docopt_help() {
        let cmd = parse_help(DOCOPT_HELP);
        assert_eq!(cmd.name.as_deref(), Some("naval_fate"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--speed"));
        assert!(longs.contains(&"--moored"));
        assert!(longs.contains(&"--drifting"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        assert_eq!(
            arg_by_long(&cmd, "--speed").and_then(|a| a.value_type.as_deref()),
            Some("kn")
        );
    }

    const GIT_HELP: &str = r#"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [--no-replace-objects] [--bare] [--git-dir=<path>] [--work-tree=<path>]
           <command> [<args>]

Usage: git [OPTIONS] <COMMAND>

Commands:
  clone     Clone a repository into a new directory
  init      Create an empty Git repository or reinitialize an existing one
  add       Add file contents to the index
  rm        Remove files from the working tree and from the index
  diff      Show changes between commits, commit and working tree, etc
  log       Show the commit logs
  status    Show the working tree status
  branch    List, create, or delete branches
  commit    Record changes to the repository
  merge     Join two or more development histories together
  rebase    Reapply commits on top of another base tip
  reset     Reset current HEAD to the specified state
  fetch     Download objects and refs from another repository
  pull      Fetch from and integrate with another repository or a local branch
  push      Update remote refs along with associated objects
  tag       Create, list, delete or verify a tag object signed with GPG

Options:
  -C <path>                Run as if git was started in <path>
  -c <name>=<value>        Pass a configuration parameter to the command
  -v, --version            Print the Git suite version
  -h, --help               Print help
"#;

    #[test]
    fn test_git_help() {
        let cmd = parse_help(GIT_HELP);
        assert_eq!(cmd.name.as_deref(), Some("git"));

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"clone"));
        assert!(subs.contains(&"commit"));
        assert!(subs.contains(&"log"));
        assert!(subs.contains(&"diff"));
        assert!(subs.contains(&"push"));
        assert!(subs.contains(&"pull"));
        assert!(subs.contains(&"branch"));
        assert!(subs.contains(&"status"));

        assert_eq!(
            subcommand_by_name(&cmd, "clone").and_then(|s| s.description.as_deref()),
            Some("Clone a repository into a new directory")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "commit").and_then(|s| s.description.as_deref()),
            Some("Record changes to the repository")
        );
    }

    const GIT_LOG_HELP: &str = r#"usage: git log [<options>] [<revision-range>] [[--] <path>...]

    -q, --quiet           Suppress diff output
    -v, --verbose         Be more verbose
    -n, --max-count <n>   Limit the number of commits to output
    --skip <n>            Skip number commits before starting to show output
    --since <date>        Show commits more recent than a specific date
    --after <date>        Show commits more recent than a specific date (alias)
    --until <date>        Show commits older than a specific date
    --before <date>       Show commits older than a specific date (alias)
    --author <pattern>    Limit output to commits with matching author
    --committer <pattern> Limit output to commits with matching committer
    --grep <pattern>      Limit commit output to ones matching the pattern
    --all-match           Limit output to commits matching all grep patterns
    -i, --regexp-ignore-case
                          Case insensitive match
    --oneline             Show one commit per line with abbreviated hash
    --no-walk             Only show given commits, not their parents
    --graph               Show the commit graph as ASCII art
    --decorate            Decorate refs
    --first-parent        Follow only the first parent commit upon merges
    -p, --patch           Show patch
    -s, --no-patch        Suppress diff output
    --stat                Generate a diffstat
    --format <format>     Pretty-print in given format
    --abbrev-commit       Show only a partial commit hash prefix
"#;

    #[test]
    fn test_git_log_help() {
        let cmd = parse_help(GIT_LOG_HELP);
        assert_eq!(cmd.name.as_deref(), Some("git"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-q"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-n"));
        assert!(shorts.contains(&"-p"));
        assert!(shorts.contains(&"-s"));
        assert!(shorts.contains(&"-i"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--max-count"));
        assert!(longs.contains(&"--since"));
        assert!(longs.contains(&"--author"));
        assert!(longs.contains(&"--grep"));
        assert!(longs.contains(&"--oneline"));
        assert!(longs.contains(&"--graph"));
        assert!(longs.contains(&"--stat"));
        assert!(longs.contains(&"--first-parent"));
        assert!(longs.contains(&"--patch"));
        assert!(longs.contains(&"--no-patch"));

        assert_eq!(
            arg_by_long(&cmd, "--max-count").and_then(|a| a.value_type.as_deref()),
            Some("n")
        );
        assert_eq!(
            arg_by_long(&cmd, "--since").and_then(|a| a.value_type.as_deref()),
            Some("date")
        );
        assert_eq!(
            arg_by_long(&cmd, "--author").and_then(|a| a.value_type.as_deref()),
            Some("pattern")
        );

        assert!(
            arg_by_long(&cmd, "--graph")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("ASCII")
        );
    }

    const GIT_COMMIT_HELP: &str = r#"usage: git commit [-a | --interactive | --patch] [-s] [-v] [--amend]
   [--author=<author>] [--date=<date>] [-m <msg>] [--no-verify]

    -q, --quiet           Suppress summary after successful commit
    -v, --verbose         Show diff in commit message template
    -F, --file <file>     Read message from file
    --author <author>     Override author for commit
    --date <date>         Override date for commit
    -m, --message <message>
                          Commit message
    -s, --signoff         Add a Signed-off-by trailer
    -e, --edit            Force edit of commit
    --cleanup <mode>      How to strip spaces and #comments from message
    --no-verify           Bypass pre-commit and commit-msg hooks
    --allow-empty         Allow recording an empty commit
    --allow-empty-message
                          Allow recording a commit with an empty message
    --amend               Amend previous commit
    -a, --all             Commit all changed files
    -i, --include         Add specified files to index for commit
    -o, --only            Commit only specified files
    --dry-run             Show what would be committed
    --short               Show status concisely
    --branch              Show branch information
    --squash <commit>     Use autosquash formatted message to squash specified commit
    --fixup <commit>      Use autosquash formatted message to fixup specified commit
"#;

    #[test]
    fn test_git_commit_help() {
        let cmd = parse_help(GIT_COMMIT_HELP);
        assert_eq!(cmd.name.as_deref(), Some("git"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-q"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-m"));
        assert!(shorts.contains(&"-a"));
        assert!(shorts.contains(&"-s"));
        assert!(shorts.contains(&"-e"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--message"));
        assert!(longs.contains(&"--author"));
        assert!(longs.contains(&"--amend"));
        assert!(longs.contains(&"--no-verify"));
        assert!(longs.contains(&"--allow-empty"));
        assert!(longs.contains(&"--dry-run"));
        assert!(longs.contains(&"--squash"));
        assert!(longs.contains(&"--signoff"));

        assert_eq!(
            arg_by_long(&cmd, "--message").and_then(|a| a.value_type.as_deref()),
            Some("message")
        );
        assert_eq!(
            arg_by_long(&cmd, "--file").and_then(|a| a.value_type.as_deref()),
            Some("file")
        );
    }

    const GIT_DIFF_HELP: &str = r#"usage: git diff [<options>] [<commit>] [--] [<path>...]
   or: git diff [<options>] --cached [<commit>] [--] [<path>...]
   or: git diff [<options>] <commit>...<commit> [--] [<path>...]

    -p, --patch           Show patch
    -s, --no-patch        Suppress diff output
    --raw                 Generate the diff in raw format
    --minimal             Produce the smallest possible diff
    --patience            Use the patience diff algorithm
    --histogram           Use the histogram diff algorithm
    --diff-algorithm <algorithm>
                          Choose a diff algorithm
    --stat                Generate a diffstat
    --compact-summary     Generate a compact summary in diffstat
    --numstat             Generate a diffstat in machine-readable form
    --shortstat           Output only the last line of --stat format
    --name-only           Show only names of changed files
    --name-status         Show only names and status of changed files
    --color <when>        Show colored diff (always, never, auto)
    --no-color            Turn off colored diff
    --word-diff <mode>    Show a word diff using the given mode
    -U, --unified <n>     Generate diffs with <n> lines of context
    --cached              View the changes staged for the next commit
    -W, --function-context
                          Show whole surrounding functions of changes
"#;

    #[test]
    fn test_git_diff_help() {
        let cmd = parse_help(GIT_DIFF_HELP);
        assert_eq!(cmd.name.as_deref(), Some("git"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-p"));
        assert!(shorts.contains(&"-s"));
        assert!(shorts.contains(&"-U"));
        assert!(shorts.contains(&"-W"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--patch"));
        assert!(longs.contains(&"--no-patch"));
        assert!(longs.contains(&"--stat"));
        assert!(longs.contains(&"--name-only"));
        assert!(longs.contains(&"--cached"));
        assert!(longs.contains(&"--word-diff"));
        assert!(longs.contains(&"--color"));
        assert!(longs.contains(&"--unified"));
    }

    #[test]
    fn test_subcommand_synthesis_overlay() {
        let help_runner = |args: &[&str]| -> anyhow::Result<String> {
            let text = match args {
                [] => GIT_HELP,
                ["log"] => GIT_LOG_HELP,
                ["commit"] => GIT_COMMIT_HELP,
                ["diff"] => GIT_DIFF_HELP,
                _ => "",
            };
            Ok(text.to_string())
        };
        let top = synthesize_completion("git", help_runner, SynthesisStrategy::RunHelp).unwrap();

        assert!(subcommand_names(&top).contains(&"log"));
        assert!(subcommand_names(&top).contains(&"commit"));

        let log_sub = subcommand_by_name(&top, "log").expect("log subcommand should exist");
        assert!(long_names(log_sub).contains(&"--oneline"));
        assert!(long_names(log_sub).contains(&"--graph"));
        assert!(long_names(log_sub).contains(&"--since"));

        let commit_sub =
            subcommand_by_name(&top, "commit").expect("commit subcommand should exist");
        assert!(long_names(commit_sub).contains(&"--amend"));
        assert!(long_names(commit_sub).contains(&"--message"));
        assert!(long_names(commit_sub).contains(&"--no-verify"));

        let diff_sub = subcommand_by_name(&top, "diff").expect("diff subcommand should exist");
        assert!(long_names(diff_sub).contains(&"--cached"));
        assert!(long_names(diff_sub).contains(&"--stat"));
    }

    const GIT_REMOTE_HELP: &str = r#"Usage: git remote [OPTIONS] <COMMAND>

Commands:
  add      Add a remote
  set-url  Changes URLs for the remote
  remove   Remove a remote
  rename   Rename a remote

Options:
  -v, --verbose    Be verbose
  -h, --help       Print help
"#;

    const GIT_REMOTE_ADD_HELP: &str = r#"usage: git remote add <name> <url>

    -f, --fetch        Fetch after adding the remote
    -t, --track <branch>
                       Track given branch
    --tags             Import all tags
    --no-tags          Do not import tags
"#;

    const GIT_REMOTE_SET_URL_HELP: &str = r#"usage: git remote set-url [--push] <name> <new-url>

    --push             Manipulate push URLs
    --add              Add URL to list
    --delete           Delete URL
"#;

    const GIT_WITH_REMOTE_HELP: &str = r#"Usage: git [OPTIONS] <COMMAND>

Commands:
  clone   Clone a repository into a new directory
  remote  Manage set of tracked repositories

Options:
  -h, --help  Print help
"#;

    #[test]
    fn test_nested_subcommand_synthesis_simulation() {
        let help_runner = |args: &[&str]| -> anyhow::Result<String> {
            let text = match args {
                [] => GIT_WITH_REMOTE_HELP,
                ["remote"] => GIT_REMOTE_HELP,
                ["remote", "add"] => GIT_REMOTE_ADD_HELP,
                ["remote", "set-url"] => GIT_REMOTE_SET_URL_HELP,
                _ => "",
            };
            Ok(text.to_string())
        };
        let top = synthesize_completion("git", help_runner, SynthesisStrategy::RunHelp).unwrap();

        let remote =
            subcommand_by_name(&top, "remote").expect("remote subcommand should be present");
        assert!(long_names(remote).contains(&"--verbose"));

        let remote_add =
            subcommand_by_name(remote, "add").expect("remote add subcommand should be present");
        assert!(long_names(remote_add).contains(&"--fetch"));
        assert!(short_names(remote_add).contains(&"-f"));
        assert_eq!(
            arg_by_long(remote_add, "--track").and_then(|a| a.value_type.as_deref()),
            Some("branch")
        );

        let remote_set_url = subcommand_by_name(remote, "set-url")
            .expect("remote set-url subcommand should be present");
        assert!(long_names(remote_set_url).contains(&"--push"));
        assert!(long_names(remote_set_url).contains(&"--delete"));
    }

    const READELF_HELP: &str = r#"Usage: readelf <option(s)> elf-file(s)
 Display information about the contents of ELF format files
 Options are:
  -a --all               Equivalent to: -h -l -S -s -r -d -V -A -I
  -h --file-header       Display the ELF file header
  -l --program-headers   Display the program headers
     --segments          An alias for --program-headers
  -S --section-headers   Display the sections' header
     --sections          An alias for --section-headers
  -g --section-groups    Display the section groups
  -t --section-details   Display the section details
  -e --headers           Equivalent to: -h -l -S
  -s --syms              Display the symbol table
     --symbols           An alias for --syms
     --dyn-syms          Display the dynamic symbol table
     --lto-syms          Display LTO symbol tables
     --sym-base=[0|8|10|16] 
                         Force base for symbol sizes.  The options are 
                         mixed (the default), octal, decimal, hexadecimal.
  -C --demangle[=STYLE]  Decode mangled/processed symbol names
                           STYLE can be "none", "auto", "gnu-v3", "java",
                           "gnat", "dlang", "rust"
     --no-demangle       Do not demangle low-level symbol names.  (default)
     --recurse-limit     Enable a demangling recursion limit.  (default)
     --no-recurse-limit  Disable a demangling recursion limit
  -n --notes             Display the contents of note sections (if present)
  -r --relocs            Display the relocations (if present)
  -u --unwind            Display the unwind info (if present)
  -d --dynamic           Display the dynamic section (if present)
  -V --version-info      Display the version sections (if present)
  -A --arch-specific     Display architecture specific information (if any)
  -c --archive-index     Display the symbol/file index in an archive
  -D --use-dynamic       Use the dynamic section info when displaying symbols
  -L --lint|--enable-checks
                         Display warning messages for possible problems
  -x --hex-dump=<number|name>
                         Dump the contents of section <number|name> as bytes
  -p --string-dump=<number|name>
                         Dump the contents of section <number|name> as strings
  -R --relocated-dump=<number|name>
                         Dump the relocated contents of section <number|name>
  -z --decompress        Decompress section before dumping it
  -I --histogram         Display histogram of bucket list lengths
  -W --wide              Allow output width to exceed 80 characters
  -T --silent-truncation If a symbol name is truncated, do not add [...] suffix
  -H --help              Display this information
  -v --version           Display the version number of readelf
Report bugs to <https://sourceware.org/bugzilla/>
"#;

    #[test]
    fn test_readelf_help() {
        let cmd = parse_help(READELF_HELP);
        assert_eq!(cmd.name.as_deref(), Some("readelf"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-a"));
        assert!(shorts.contains(&"-h"));
        assert!(shorts.contains(&"-l"));
        assert!(shorts.contains(&"-S"));
        assert!(shorts.contains(&"-r"));
        assert!(shorts.contains(&"-d"));
        assert!(shorts.contains(&"-n"));
        assert!(shorts.contains(&"-W"));
        assert!(shorts.contains(&"-H"));
        assert!(shorts.contains(&"-v"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--all"));
        assert!(longs.contains(&"--file-header"));
        assert!(longs.contains(&"--program-headers"));
        assert!(longs.contains(&"--section-headers"));
        assert!(longs.contains(&"--relocs"));
        assert!(longs.contains(&"--dynamic"));
        assert!(longs.contains(&"--notes"));
        assert!(longs.contains(&"--wide"));
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--hex-dump"));

        assert_eq!(
            arg_by_long(&cmd, "--hex-dump").and_then(|a| a.value_type.as_deref()),
            Some("number|name")
        );
    }

    #[test]
    fn test_parse_flag_tokens_ignores_multi_character_short_forms() {
        let (short, long, value_type) = parse_flag_tokens("-wk --debug-dump=links");
        assert_eq!(short, None);
        assert_eq!(long.as_deref(), Some("--debug-dump"));
        assert_eq!(value_type.as_deref(), Some("links"));

        let (short, long, value_type) =
            parse_flag_tokens("-U[dlexhi] --unicode=[default|locale|escape|hex|highlight|invalid]");
        assert_eq!(short, None);
        assert_eq!(long.as_deref(), Some("--unicode"));
        assert_eq!(
            value_type.as_deref(),
            Some("[default|locale|escape|hex|highlight|invalid]")
        );
    }
    #[test]
    fn test_zstd_help() {
        const HELP: &str = r#"*** Zstandard CLI (64-bit) v1.5.5, by Yann Collet ***

Compress or decompress the INPUT file(s); reads from STDIN if INPUT is `-` or not provided.

Usage: zstd [OPTIONS...] [INPUT... | -] [-o OUTPUT]

Options:
  -o OUTPUT                     Write output to a single file, OUTPUT.
  -k, --keep                    Preserve INPUT file(s). [Default]
  --rm                          Remove INPUT file(s) after successful (de)compression.
  -#                            Desired compression level, where `#` is a number between 1 and 19;
                                lower numbers provide faster compression, higher numbers yield
                                better compression ratios. [Default: 3]

  -d, --decompress              Perform decompression.
  -D DICT                       Use DICT as the dictionary for compression or decompression.

  -f, --force                   Disable input and output checks. Allows overwriting existing files,
                                receiving input from the console, printing output to STDOUT, and
                                operating on links, block devices, etc. Unrecognized formats will be
                                passed-through through as-is.

  -h                            Display short usage and exit.
  -H, --help                    Display full help and exit.
  -V, --version                 Display the program version and exit.

Advanced options:
  -c, --stdout                  Write to STDOUT (even if it is a console) and keep the INPUT file(s).

  -v, --verbose                 Enable verbose output; pass multiple times to increase verbosity.
  -q, --quiet                   Suppress warnings; pass twice to suppress errors.
  --trace LOG                   Log tracing information to LOG.

  --[no-]progress               Forcibly show/hide the progress counter. NOTE: Any (de)compressed
                                output to terminal will mix with progress counter text.

  -r                            Operate recursively on directories.
  --filelist LIST               Read a list of files to operate on from LIST.
  --output-dir-flat DIR         Store processed files in DIR.
  --output-dir-mirror DIR       Store processed files in DIR, respecting original directory structure.
  --[no-]asyncio                Use asynchronous IO. [Default: Enabled]

  --[no-]check                  Add XXH64 integrity checksums during compression. [Default: Add, Validate]
                                If `-d` is present, ignore/validate checksums during decompression.

  --                            Treat remaining arguments after `--` as files.

Advanced compression options:
  --ultra                       Enable levels beyond 19, up to 22; requires more memory.
  --fast[=#]                    Use to very fast compression levels. [Default: 1]
  --adapt                       Dynamically adapt compression level to I/O conditions.
  --long[=#]                    Enable long distance matching with window log #. [Default: 27]
  --patch-from=REF              Use REF as the reference point for Zstandard's diff engine.

  -T#                           Spawn # compression threads. [Default: 1; pass 0 for core count.]
  --single-thread               Share a single thread for I/O and compression (slightly different than `-T1`).
  --auto-threads={physical|logical}
                                Use physical/logical cores when using `-T0`. [Default: Physical]

  -B#                           Set job size to #. [Default: 0 (automatic)]
  --rsyncable                   Compress using a rsync-friendly method (`-B` sets block size).

  --exclude-compressed          Only compress files that are not already compressed.

  --stream-size=#               Specify size of streaming input from STDIN.
  --size-hint=#                 Optimize compression parameters for streaming input of approximately size #.
  --target-compressed-block-size=#
                                Generate compressed blocks of approximately # size.

  --no-dictID                   Don't write `dictID` into the header (dictionary compression only).
  --[no-]compress-literals      Force (un)compressed literals.
  --[no-]row-match-finder       Explicitly enable/disable the fast, row-based matchfinder for
                                the 'greedy', 'lazy', and 'lazy2' strategies.

  --format=zstd                 Compress files to the `.zst` format. [Default]
  --mmap-dict                   Memory-map dictionary file rather than mallocing and loading all at once  --format=gzip                 Compress files to the `.gz` format.
  --format=xz                   Compress files to the `.xz` format.
  --format=lzma                 Compress files to the `.lzma` format.
  --format=lz4                 Compress files to the `.lz4` format.

Advanced decompression options:
  -l                            Print information about Zstandard-compressed files.
  --test                        Test compressed file integrity.
  -M#                           Set the memory usage limit to # megabytes.
  --[no-]sparse                 Enable sparse mode. [Default: Enabled for files, disabled for STDOUT.]
  --[no-]pass-through           Pass through uncompressed files as-is. [Default: Disabled]

Dictionary builder:
  --train                       Create a dictionary from a training set of files.

  --train-cover[=k=#,d=#,steps=#,split=#,shrink[=#]]
                                Use the cover algorithm (with optional arguments).
  --train-fastcover[=k=#,d=#,f=#,steps=#,split=#,accel=#,shrink[=#]]
                                Use the fast cover algorithm (with optional arguments).

  --train-legacy[=s=#]          Use the legacy algorithm with selectivity #. [Default: 9]
  -o NAME                       Use NAME as dictionary name. [Default: dictionary]
  --maxdict=#                   Limit dictionary to specified size #. [Default: 112640]
  --dictID=#                    Force dictionary ID to #. [Default: Random]

Benchmark options:
  -b#                           Perform benchmarking with compression level #. [Default: 3]
  -e#                           Test all compression levels up to #; starting level is `-b#`. [Default: 1]
  -i#                           Set the minimum evaluation to time # seconds. [Default: 3]
  -B#                           Cut file into independent chunks of size #. [Default: No chunking]
  -S                            Output one benchmark result per input file. [Default: Consolidated result]
  --priority=rt                 Set process priority to real-time.
"#;
        let cmd = parse_help(HELP);

        // Check overall commands info
        assert_eq!(
            cmd.description.as_deref(),
            Some(
                "Compress or decompress the INPUT file(s); reads from STDIN if INPUT is `-` or not provided."
            )
        );

        let args = &cmd.args;

        // Assertions on various options to ensure correct parsing
        let o_arg = args
            .iter()
            .find(|a| a.short.as_deref() == Some("-o") && a.value_type.as_deref() == Some("OUTPUT"))
            .unwrap();
        assert!(
            o_arg
                .description
                .as_ref()
                .unwrap()
                .contains("Write output to a single file")
        );

        let keep_arg = args
            .iter()
            .find(|a| a.long.as_deref() == Some("--keep"))
            .unwrap();
        assert_eq!(keep_arg.short.as_deref(), Some("-k"));
        assert!(
            keep_arg
                .description
                .as_ref()
                .unwrap()
                .contains("Preserve INPUT file(s)")
        );

        let rm_arg = args
            .iter()
            .find(|a| a.long.as_deref() == Some("--rm"))
            .unwrap();
        assert!(
            rm_arg
                .description
                .as_ref()
                .unwrap()
                .contains("Remove INPUT file(s) after successful")
        );

        let level_arg = args
            .iter()
            .find(|a| a.short.as_deref() == Some("-#") || a.long.as_deref() == Some("-#"))
            .unwrap();
        assert!(
            level_arg
                .description
                .as_ref()
                .unwrap()
                .contains("Desired compression level")
        );

        let dict_arg = args
            .iter()
            .find(|a| a.short.as_deref() == Some("-D"))
            .unwrap();
        assert_eq!(dict_arg.value_type.as_deref(), Some("DICT"));

        let trace_arg = args
            .iter()
            .find(|a| a.long.as_deref() == Some("--trace"))
            .unwrap();
        assert_eq!(trace_arg.value_type.as_deref(), Some("LOG"));

        let format_arg = args
            .iter()
            .find(|a| a.long.as_deref() == Some("--format"))
            .unwrap();
        assert_eq!(format_arg.value_type.as_deref(), Some("zstd"));

        let test_arg = args
            .iter()
            .find(|a| a.long.as_deref() == Some("--test"))
            .unwrap();
        assert!(
            test_arg
                .description
                .as_ref()
                .unwrap()
                .contains("Test compressed file integrity")
        );

        let train_arg = args
            .iter()
            .find(|a| a.long.as_deref() == Some("--train"))
            .unwrap();
        assert!(
            train_arg
                .description
                .as_ref()
                .unwrap()
                .contains("Create a dictionary from a training set")
        );

        let threads_arg = args
            .iter()
            .find(|a| a.short.as_deref() == Some("-T#"))
            .unwrap();
        assert!(
            threads_arg
                .description
                .as_ref()
                .unwrap()
                .contains("Spawn # compression threads")
        );
    }

    #[test]
    fn test_expand_no_options_in_help() {
        const HELP: &str = r#"Usage: mytool [OPTIONS]

Options:
  --[no-]color             Enable or disable color output.
  --[no]nocolor            Enable or disable nocolor option.
"#;
        let cmd = parse_help(HELP);
        let args = &cmd.args;

        // --[no-]color should expand to --color and --no-color
        assert!(args.iter().any(|a| a.long.as_deref() == Some("--color")));
        assert!(args.iter().any(|a| a.long.as_deref() == Some("--no-color")));

        // --[no]nocolor should expand to --nocolor and --nonocolor
        assert!(args.iter().any(|a| a.long.as_deref() == Some("--nocolor")));
        assert!(
            args.iter()
                .any(|a| a.long.as_deref() == Some("--nonocolor"))
        );
    }
}
