#![allow(unused)]

//! Parse a `--help` string into a [`Command`] structure.
//!
//! The entry point is [`parse_help`].  It tries to identify which help format
//! the text comes from (clap, Python argparse, or an unknown generic format)
//! and dispatches to the appropriate sub-parser.

// ──────────────────────────────────────────────────────────────────────────────
// Public data structures
// ──────────────────────────────────────────────────────────────────────────────

/// A single command-line argument / flag.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Arg {
    /// Long flag name, e.g. `--verbose`.
    pub long: Option<String>,
    /// Short flag name, e.g. `-v`.
    pub short: Option<String>,
    /// Human-readable description.
    pub description: Option<String>,
    /// Meta-variable / value type hint (e.g. `<PATH>`, `<N>`).
    pub value_type: Option<String>,
    /// Number of values accepted (e.g. `*`, `+`, `?`, or a count like `"1"`).
    pub num_args: Option<String>,
}

/// A parsed command (or sub-command).
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Command {
    /// Name of the command, if known.
    pub name: Option<String>,
    /// Author / maintainer information, if present.
    pub author: Option<String>,
    /// Short description / about line.
    pub description: Option<String>,
    /// Recognised arguments / flags.
    pub args: Vec<Arg>,
    /// Recognised sub-commands.
    pub subcommands: Vec<Command>,
}

// ──────────────────────────────────────────────────────────────────────────────
// Format detection
// ──────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum HelpFormat {
    /// Output generated by [clap](https://docs.rs/clap) (Rust).
    Clap,
    /// Output generated by Python's `argparse` module.
    Argparse,
    /// Unknown / generic format.
    Generic,
}

fn detect_format(help: &str) -> HelpFormat {
    // clap outputs a "Usage:" line (capital U) and uses long option descriptions
    // indented underneath the flag, separated by an empty line.
    let has_usage = help.contains("Usage:");
    let has_commands_section = help.contains("\nCommands:\n") || help.contains("\nSubcommands:\n");
    // argparse always prints "usage:" (lowercase) and "optional arguments:" or
    // "options:" sections.
    let has_positional = help.contains("positional arguments:");
    let has_optional = help.contains("optional arguments:") || help.contains("options:");

    if has_positional || (has_optional && !has_commands_section) {
        // Pure argparse output never has a "Commands:" section.
        HelpFormat::Argparse
    } else if has_usage || has_commands_section {
        HelpFormat::Clap
    } else {
        HelpFormat::Generic
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Public entry point
// ──────────────────────────────────────────────────────────────────────────────

/// Parse a `--help` string into a [`Command`] with the best fidelity possible.
///
/// The function auto-detects whether the string was produced by *clap*,
/// Python *argparse*, or an unknown tool, and dispatches accordingly.
pub fn parse_help(help: &str) -> Command {
    match detect_format(help) {
        HelpFormat::Clap => parse_help_clap(help),
        HelpFormat::Argparse => parse_help_argparse(help),
        HelpFormat::Generic => parse_help_generic(help),
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Helper utilities
// ──────────────────────────────────────────────────────────────────────────────

/// Leading-space count for a line (tabs count as 1).
fn indent_of(line: &str) -> usize {
    line.chars().take_while(|c| *c == ' ' || *c == '\t').count()
}

/// Try to parse a flag token like `-v`, `--verbose`, or `--output <FILE>`.
/// Returns `(short, long, value_type)`.
fn parse_flag_tokens(token: &str) -> (Option<String>, Option<String>, Option<String>) {
    // Split on commas / whitespace to handle "-v, --verbose <FILE>"
    let mut short = None;
    let mut long = None;
    let mut value_type = None;

    // Tokenise: split on ", " first, then whitespace
    let pieces: Vec<&str> = token.split_whitespace().collect();
    for piece in &pieces {
        if piece.starts_with("--") {
            // May be "--flag" or "--flag=<VAL>"
            if let Some((flag, val)) = piece.split_once('=') {
                long = Some(flag.trim_end_matches(',').to_string());
                value_type = Some(val.trim_matches(|c| c == '<' || c == '>').to_string());
            } else {
                long = Some(piece.trim_end_matches(',').to_string());
            }
        } else if let Some(short_candidate) = piece.strip_prefix('-') {
            let short_candidate = short_candidate.trim_end_matches(',');
            // Only treat single-character forms like `-v` as clap short flags.
            // Multi-character forms such as `-wk`, `-wK`, or `-U[dlexhi]` are
            // command-specific syntax, not plain one-letter short options.
            if short_candidate.chars().count() == 1 {
                short = Some(format!("-{short_candidate}"));
            }
        } else if piece.starts_with('<') || piece.starts_with('[') {
            // Meta-variable — only capture the first one found so that description
            // text like `[default: 10]` does not overwrite an already-parsed hint.
            // Subsequent bracketed tokens (e.g. `[boolean]`, `[default: …]`) are
            // intentionally ignored once a value-type has been established.
            if value_type.is_none() {
                value_type = Some(
                    piece
                        .trim_matches(|c| c == '<' || c == '>' || c == '[' || c == ']')
                        .to_string(),
                );
            }
        }
    }
    (short, long, value_type)
}

/// Collect continuation lines: lines whose indent > `base_indent` (or blank).
/// Returns the combined description string.
fn collect_continuation<'a>(
    lines: &'a [&'a str],
    start: usize,
    base_indent: usize,
) -> (String, usize) {
    let mut desc_parts = Vec::new();
    let mut i = start;
    while i < lines.len() {
        let line = lines[i];
        if line.trim().is_empty() {
            // blank line ends the block
            break;
        }
        let ind = indent_of(line);
        if ind <= base_indent {
            break;
        }
        // A deeper-indented line that starts with `-` is another flag entry,
        // not description text.  This handles tools like cargo that mix indent
        // levels within a single Options section (e.g. indent-2 for short+long
        // flags and indent-6 for long-only flags).
        if line.trim().starts_with('-') {
            break;
        }
        desc_parts.push(line.trim().to_string());
        i += 1;
    }
    (desc_parts.join(" "), i)
}

// ──────────────────────────────────────────────────────────────────────────────
// clap parser
// ──────────────────────────────────────────────────────────────────────────────

/// Parse clap-style `--help` output.
///
/// Typical structure:
/// ```text
/// <description>
///
/// Usage: <name> [OPTIONS] [COMMAND]
///
/// Commands:
///   subcommand1  Short description
///   subcommand2  Short description
///
/// Arguments:
///   [ARG]  description
///
/// Options:
///       --flag <VALUE>
///           Long description
///   -h, --help
///           Print help
/// ```
pub fn parse_help_clap(help: &str) -> Command {
    let lines: Vec<&str> = help.lines().collect();
    let mut cmd = Command::default();

    // Extract name from "Usage:" line; handles both "Usage: name ..." (clap/commander)
    // and "Usage:\n  name ..." (cobra/docopt) styles.
    if let Some(usage_pos) = lines
        .iter()
        .position(|l| l.trim_start().starts_with("Usage:"))
    {
        let after = lines[usage_pos].trim_start_matches(|c: char| c.is_whitespace());
        let after = after.strip_prefix("Usage:").unwrap_or(after).trim();
        if let Some(name_part) = after.split_whitespace().next() {
            // Standard "Usage: name ..." form.
            cmd.name = Some(name_part.to_string());
        } else {
            // Cobra/docopt form: "Usage:" is alone on its own line; name is on the next.
            for next_line in &lines[usage_pos + 1..] {
                let t = next_line.trim();
                if !t.is_empty() {
                    if let Some(name_part) = t.split_whitespace().next() {
                        cmd.name = Some(name_part.to_string());
                    }
                    break;
                }
            }
        }
    }

    // First non-empty line before "Usage:" is the description.
    let usage_pos = lines
        .iter()
        .position(|l| l.trim_start().starts_with("Usage:"))
        .unwrap_or(0);
    for line in &lines[..usage_pos] {
        let t = line.trim();
        if !t.is_empty() {
            cmd.description = Some(t.to_string());
            break;
        }
    }

    // Section parsing.
    let mut i = 0;
    while i < lines.len() {
        let trimmed = lines[i].trim();

        // ── Commands / Subcommands section ──────────────────────────────────
        if trimmed == "Commands:" || trimmed == "Subcommands:" || trimmed == "Available Commands:" {
            i += 1;
            while i < lines.len() {
                let line = lines[i];
                if line.trim().is_empty() {
                    i += 1;
                    break;
                }
                // Guard: a non-indented non-empty line is a new section header.
                if indent_of(line) == 0 && !line.trim().is_empty() {
                    break;
                }
                let trimmed_line = line.trim();
                // Format: "  subname  Short description"
                let mut parts = trimmed_line.splitn(2, "  ");
                let sub_name = parts.next().unwrap_or("").trim().to_string();
                let sub_desc = parts.next().map(|s| s.trim().to_string());
                if !sub_name.is_empty() {
                    cmd.subcommands.push(Command {
                        name: Some(sub_name),
                        description: sub_desc,
                        ..Command::default()
                    });
                }
                i += 1;
            }
            continue;
        }

        // ── Options / Arguments / Flags section ────────────────────────────
        if trimmed == "Options:"
            || trimmed == "Arguments:"
            || trimmed == "Flags:"
            || trimmed == "Global Flags:"
            || trimmed == "Global Options:"
            || trimmed == "Options are:"
        {
            i += 1;
            while i < lines.len() {
                let line = lines[i];
                if line.trim().is_empty() {
                    i += 1;
                    // blank line may separate args but we continue
                    continue;
                }
                // A non-indented non-empty line is a new section header.
                if indent_of(line) == 0 {
                    break;
                }
                let flag_indent = indent_of(line);
                let flag_part = line.trim();

                // Skip pure description continuation lines that are deeper
                // (they belong to the previous arg).
                // We identify flag lines as ones that start with '-' or '['.
                if !flag_part.starts_with('-') && !flag_part.starts_with('[') {
                    i += 1;
                    continue;
                }

                // Only parse tokens up to the first double-space to avoid
                // treating description text as flag tokens.
                let token_part = flag_part
                    .find("  ")
                    .map(|pos| &flag_part[..pos])
                    .unwrap_or(flag_part);
                let (short, long, value_type) = parse_flag_tokens(token_part);

                // Capture inline description (text after first double-space on
                // the flag line), then append any deeper-indented continuation.
                let inline_desc: Option<String> = flag_part.find("  ").and_then(|pos| {
                    let d = flag_part[pos..].trim();
                    if d.is_empty() {
                        None
                    } else {
                        Some(d.to_string())
                    }
                });
                let (cont_desc, next_i) = collect_continuation(&lines, i + 1, flag_indent);
                i = next_i;

                let description = match (inline_desc, cont_desc.as_str()) {
                    (Some(d), "") => Some(d),
                    (None, d) if !d.is_empty() => Some(d.to_string()),
                    (Some(d), rest) => Some(format!("{} {}", d, rest)),
                    (None, _) => None,
                };

                let num_args = if value_type.is_some() {
                    Some("1".to_string())
                } else {
                    None
                };

                cmd.args.push(Arg {
                    short,
                    long,
                    description,
                    value_type,
                    num_args,
                });
            }
            continue;
        }

        i += 1;
    }

    cmd
}

// ──────────────────────────────────────────────────────────────────────────────
// argparse parser
// ──────────────────────────────────────────────────────────────────────────────

/// Parse Python argparse-style `--help` output.
///
/// Typical structure:
/// ```text
/// usage: script.py [-h] [--flag VALUE] positional
///
/// Description of the program.
///
/// positional arguments:
///   positional   help text
///
/// optional arguments:
///   -h, --help   show this help message and exit
///   --flag VALUE
///                help text for flag
/// ```
pub fn parse_help_argparse(help: &str) -> Command {
    let lines: Vec<&str> = help.lines().collect();
    let mut cmd = Command::default();

    // Command name from "usage:" line.
    if let Some(usage_line) = lines
        .iter()
        .find(|l| l.trim_start().to_lowercase().starts_with("usage:"))
    {
        let after = usage_line
            .trim_start_matches(|c: char| c.is_whitespace())
            .to_lowercase();
        let after = after.strip_prefix("usage:").unwrap_or(&after).trim();
        if let Some(name) = after.split_whitespace().next() {
            cmd.name = Some(name.to_string());
        }
    }

    // Description: first non-empty line after blank line following "usage:".
    let usage_pos = lines
        .iter()
        .position(|l| l.trim_start().to_lowercase().starts_with("usage:"))
        .unwrap_or(0);
    let mut found_blank = false;
    for line in &lines[usage_pos + 1..] {
        if line.trim().is_empty() {
            found_blank = true;
        } else if found_blank {
            let t = line.trim();
            // Don't treat section headers as the description.
            if !t.ends_with(':') {
                cmd.description = Some(t.to_string());
            }
            break;
        }
    }

    // Section parsing.
    let mut i = 0;
    while i < lines.len() {
        let trimmed = lines[i].trim();

        let is_args_section = trimmed == "positional arguments:"
            || trimmed == "optional arguments:"
            || trimmed == "options:"
            || trimmed.starts_with("named arguments:");

        if is_args_section {
            i += 1;
            while i < lines.len() {
                let line = lines[i];
                if line.trim().is_empty() {
                    i += 1;
                    break;
                }
                // Non-indented line → new section.
                if indent_of(line) == 0 && line.trim().ends_with(':') {
                    break;
                }
                let flag_indent = indent_of(line);
                let flag_part = line.trim();

                // argparse flag lines start with '-' for flags or a word for positional.
                let (short, long, value_type) = if flag_part.starts_with('-') {
                    // Only parse tokens up to the first double-space to avoid
                    // treating description text as flag tokens.
                    let token_part = flag_part
                        .find("  ")
                        .map(|pos| &flag_part[..pos])
                        .unwrap_or(flag_part);
                    parse_flag_tokens(token_part)
                } else {
                    // Positional argument: first word is the name.
                    let name_token = flag_part.split_whitespace().next().unwrap_or("");
                    (None, Some(name_token.to_string()), None)
                };

                // Description may be inline (after double-space) or on continuation lines.
                let inline_desc: Option<String> = if let Some(pos) = flag_part.find("  ") {
                    let d = flag_part[pos..].trim();
                    if !d.is_empty() {
                        Some(d.to_string())
                    } else {
                        None
                    }
                } else {
                    None
                };

                let (cont_desc, next_i) = collect_continuation(&lines, i + 1, flag_indent);
                i = next_i;

                let description = match (inline_desc, cont_desc.as_str()) {
                    (Some(d), "") => Some(d),
                    (None, d) if !d.is_empty() => Some(d.to_string()),
                    (Some(d), rest) => Some(format!("{} {}", d, rest)),
                    (None, _) => None,
                };

                let num_args = if value_type.is_some() {
                    Some("1".to_string())
                } else {
                    None
                };

                cmd.args.push(Arg {
                    short,
                    long,
                    description,
                    value_type,
                    num_args,
                });
            }
            continue;
        }

        i += 1;
    }

    cmd
}

// ──────────────────────────────────────────────────────────────────────────────
// Generic / fallback parser
// ──────────────────────────────────────────────────────────────────────────────

/// Fallback parser for unrecognised help formats.
///
/// Uses heuristics:
/// - Lines that start with `-` are treated as argument definitions.
/// - A two-space-separated suffix on such a line is the inline description.
/// - Deeper-indented lines following a flag are appended to its description.
pub fn parse_help_generic(help: &str) -> Command {
    let lines: Vec<&str> = help.lines().collect();
    let mut cmd = Command::default();

    // Try to find a name from the first "usage"/"Usage" line.
    for line in &lines {
        let lower = line.trim().to_lowercase();
        if lower.starts_with("usage:") {
            let after = line
                .trim()
                .trim_start_matches(|c: char| c.is_alphabetic() || c == ':')
                .trim();
            if let Some(name) = after.split_whitespace().next() {
                cmd.name = Some(name.to_string());
                break;
            }
        }
    }

    // Collect description from the first non-empty line if it doesn't look
    // like a flag or section header.
    for line in &lines {
        let t = line.trim();
        if !t.is_empty() && !t.starts_with('-') && !t.to_lowercase().starts_with("usage:") {
            cmd.description = Some(t.to_string());
            break;
        }
    }

    // Scan for argument lines.
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        let flag_part = line.trim();

        if flag_part.starts_with('-') {
            let flag_indent = indent_of(line);
            // Only parse tokens up to the first double-space to avoid
            // treating description text as flag tokens.
            let token_part = flag_part
                .find("  ")
                .map(|pos| &flag_part[..pos])
                .unwrap_or(flag_part);
            let (short, long, value_type) = parse_flag_tokens(token_part);

            let inline_desc: Option<String> = if let Some(pos) = flag_part.find("  ") {
                let d = flag_part[pos..].trim();
                if !d.is_empty() {
                    Some(d.to_string())
                } else {
                    None
                }
            } else {
                None
            };

            let (cont_desc, next_i) = collect_continuation(&lines, i + 1, flag_indent);
            i = next_i;

            let description = match (inline_desc, cont_desc.as_str()) {
                (Some(d), "") => Some(d),
                (None, d) if !d.is_empty() => Some(d.to_string()),
                (Some(d), rest) => Some(format!("{} {}", d, rest)),
                (None, _) => None,
            };

            let num_args = if value_type.is_some() {
                Some("1".to_string())
            } else {
                None
            };

            cmd.args.push(Arg {
                short,
                long,
                description,
                value_type,
                num_args,
            });
            continue;
        }

        i += 1;
    }

    cmd
}

// ──────────────────────────────────────────────────────────────────────────────
// Clap command conversion
// ──────────────────────────────────────────────────────────────────────────────

/// Leak a [`String`] into a `&'static str`.
///
/// This is used when building a dynamic [`clap::Command`] structure at runtime,
/// because clap 4.x's builder methods (`.long()`, `.about()`, `.help()`,
/// `.value_name()`) require `&'static str` references.  The leak is intentional
/// and acceptable because `to_clap_command` is only called from the one-shot
/// `comp-spec-synthesis` subcommand.
fn leak_string(s: String) -> &'static str {
    Box::leak(s.into_boxed_str())
}

/// Convert a parsed [`Command`] tree into a [`clap::Command`] that can be used
/// to generate shell completion scripts via [`clap_complete`].
///
/// Argument names are derived from the long flag (stripping the leading `--`),
/// falling back to the short flag (stripping `-`), and finally `"arg"` for
/// purely positional arguments.  Short and long flags are attached when present.
/// `value_type` is used as the `value_name` meta-variable and also implies
/// `num_args(1)` unless `num_args` overrides it explicitly.
pub fn to_clap_command(cmd: &Command) -> clap::Command {
    let name = leak_string(cmd.name.as_deref().unwrap_or("unknown").to_string());
    let mut clap_cmd = clap::Command::new(name)
        // The parsed args already include `--help`/`--version` when present, so
        // disable clap's auto-generated flags to avoid duplicate-name panics.
        .disable_help_flag(true)
        .disable_version_flag(true);

    if let Some(desc) = &cmd.description {
        clap_cmd = clap_cmd.about(leak_string(desc.clone()));
    }

    let mut used_short_flags = std::collections::HashSet::new();
    let mut used_long_flags = std::collections::HashSet::new();
    let mut used_arg_ids = std::collections::HashSet::new();

    for arg in &cmd.args {
        // Strip leading dashes from the long flag once; reuse for both the
        // argument identifier and the `.long()` call.
        let long_bare: Option<String> = arg
            .long
            .as_deref()
            .map(|l| l.trim_start_matches('-').to_string());

        if let Some(long) = &long_bare {
            if !used_long_flags.insert(long.clone()) {
                log::debug!(
                    "comp-spec-synthesis: dropping duplicate long flag '--{}'",
                    long
                );
                continue;
            }
        }

        // Derive a stable identifier for the argument, then make it unique for
        // clap even when the parsed help contains repeated or unnamed args.
        let base_id = long_bare
            .clone()
            .or_else(|| {
                arg.short
                    .as_deref()
                    .map(|s| s.trim_start_matches('-').to_string())
            })
            .unwrap_or_else(|| "arg".to_string());

        let mut id = base_id.clone();
        let mut suffix = 2;
        while !used_arg_ids.insert(id.clone()) {
            id = format!("{}-{}", base_id, suffix);
            suffix += 1;
        }

        let id = leak_string(id);

        let mut clap_arg = clap::Arg::new(id);

        if let Some(long) = &long_bare {
            clap_arg = clap_arg.long(leak_string(long.clone()));
        }

        if let Some(short) = &arg.short {
            if let Some(c) = short.trim_start_matches('-').chars().next() {
                if used_short_flags.insert(c) {
                    clap_arg = clap_arg.short(c);
                } else {
                    log::debug!(
                        "comp-spec-synthesis: dropping duplicate short flag '-{}' for arg {:?}",
                        c,
                        id
                    );
                }
            }
        }

        if let Some(desc) = &arg.description {
            clap_arg = clap_arg.help(leak_string(desc.clone()));
        }

        if let Some(value_type) = &arg.value_type {
            // Strip surrounding angle-brackets if present (e.g. `<PATH>` → `PATH`).
            let meta = leak_string(
                value_type
                    .trim_matches(|c| c == '<' || c == '>')
                    .to_string(),
            );
            clap_arg = clap_arg.value_name(meta);
            // A value type implies the flag accepts exactly one value by default;
            // this may be overridden below by an explicit `num_args`.
            clap_arg = clap_arg.num_args(1);
        }

        if let Some(num_args_str) = &arg.num_args {
            clap_arg = match num_args_str.as_str() {
                "*" => clap_arg.num_args(0..),
                "+" => clap_arg.num_args(1..),
                "?" => clap_arg.num_args(0..=1),
                s => {
                    if let Ok(n) = s.parse::<usize>() {
                        clap_arg.num_args(n)
                    } else {
                        clap_arg
                    }
                }
            };
        }

        clap_cmd = clap_cmd.arg(clap_arg);
    }

    for sub in &cmd.subcommands {
        clap_cmd = clap_cmd.subcommand(to_clap_command(sub));
    }

    clap_cmd
}

// ──────────────────────────────────────────────────────────────────────────────
// Synthesis: run a command and build its completion spec
// ──────────────────────────────────────────────────────────────────────────────

/// Invoke `help_runner` to obtain help text, parse it, and flesh out each
/// discovered subcommand by calling `help_runner` again with the subcommand
/// path.  Subcommands are explored iteratively using a work-stack so that
/// nested subcommands (sub-sub-commands, etc.) are also populated, up to a
/// maximum nesting depth of [`MAX_SUBCOMMAND_DEPTH`].
///
/// The `name` field of the returned [`Command`] is always set to the basename
/// of `command_path` so that the generated completion script uses the correct
/// name regardless of what the help text says.
///
/// `help_runner` is called with the subcommand path (e.g. `&["remote", "add"]`)
/// and must return the corresponding `--help` output.  For the top-level
/// command the slice is empty (`&[]`).
pub fn synthesize_completion<F>(command_path: &str, help_runner: F) -> anyhow::Result<Command>
where
    F: Fn(&[&str]) -> anyhow::Result<String>,
{
    // ── top-level help ───────────────────────────────────────────────────────
    let top_help = help_runner(&[])?;
    let mut root = parse_help(&top_help);

    // Always use the basename of the supplied path as the canonical name.
    let cmd_name = std::path::Path::new(command_path)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or(command_path)
        .to_string();
    root.name = Some(cmd_name);

    // ── iterative subcommand exploration ─────────────────────────────────────
    // Each stack entry is a path of subcommand names from the root, e.g.
    // `["remote", "add"]`.  We use this path both to locate the node in the
    // `Command` tree and to build the argv for the `--help` invocation.
    // Five levels of nesting covers the vast majority of real CLI tools while
    // keeping synthesis time bounded.
    const MAX_SUBCOMMAND_DEPTH: usize = 5;

    // Seed the stack with every top-level subcommand.
    let mut stack: Vec<Vec<String>> = root
        .subcommands
        .iter()
        .filter_map(|s| s.name.clone().map(|n| vec![n]))
        .collect();

    while let Some(path) = stack.pop() {
        if path.len() > MAX_SUBCOMMAND_DEPTH {
            continue;
        }

        // Build the argv slice for the help invocation.
        let path_strs: Vec<&str> = path.iter().map(String::as_str).collect();
        let help_output = match help_runner(&path_strs) {
            Ok(s) if !s.trim().is_empty() => s,
            Ok(_) => continue,
            Err(e) => {
                log::debug!(
                    "comp-spec-synthesis: skipping '{}': {}",
                    path_strs.join(" "),
                    e
                );
                continue;
            }
        };

        let parsed = parse_help(&help_output);

        // Navigate to the target node in the tree and update it.
        if let Some(node) = find_subcommand_mut(&mut root, &path) {
            // Push newly discovered sub-subcommands onto the stack before
            // overwriting them so we can explore them later.
            for child in &parsed.subcommands {
                if let Some(child_name) = &child.name {
                    let mut child_path = path.clone();
                    child_path.push(child_name.clone());
                    stack.push(child_path);
                }
            }

            node.args = parsed.args;
            node.subcommands = parsed.subcommands;
            if node.description.is_none() {
                node.description = parsed.description;
            }
        }
    }

    Ok(root)
}

/// Navigate the [`Command`] tree following `path` (a slice of subcommand
/// names) and return a mutable reference to the deepest node, or `None` if
/// any step along the path cannot be found.
fn find_subcommand_mut<'a>(root: &'a mut Command, path: &[String]) -> Option<&'a mut Command> {
    let mut current = root;
    for name in path {
        current = current
            .subcommands
            .iter_mut()
            .find(|s| s.name.as_deref() == Some(name.as_str()))?;
    }
    Some(current)
}

/// Invoke `command_path [extra_args...] --help` and return the combined output.
///
/// Many tools print their help to *stderr* rather than *stdout*; this function
/// returns whichever stream is non-empty (preferring stdout).
pub(crate) fn run_help(command_path: &str, extra_args: &[&str]) -> anyhow::Result<String> {
    let output = std::process::Command::new(command_path)
        .args(extra_args)
        .arg("--help")
        .output()
        .map_err(|e| anyhow::anyhow!("failed to run '{}': {}", command_path, e))?;

    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    let stderr = String::from_utf8_lossy(&output.stderr).into_owned();

    // Some tools (e.g. git) write help to stdout when `--help` is passed as a
    // flag, but others write to stderr.  Prefer stdout when it has content.
    Ok(if stdout.trim().is_empty() {
        stderr
    } else {
        stdout
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── helpers ──────────────────────────────────────────────────────────────

    /// Returns the long names of all args in `cmd`.
    fn long_names(cmd: &Command) -> Vec<&str> {
        cmd.args.iter().filter_map(|a| a.long.as_deref()).collect()
    }

    /// Returns the short names of all args in `cmd`.
    fn short_names(cmd: &Command) -> Vec<&str> {
        cmd.args.iter().filter_map(|a| a.short.as_deref()).collect()
    }

    /// Returns the names of all sub-commands in `cmd`.
    fn subcommand_names(cmd: &Command) -> Vec<&str> {
        cmd.subcommands
            .iter()
            .filter_map(|s| s.name.as_deref())
            .collect()
    }

    /// Looks up an arg by its long name.
    fn arg_by_long<'a>(cmd: &'a Command, long: &str) -> Option<&'a Arg> {
        cmd.args.iter().find(|a| a.long.as_deref() == Some(long))
    }

    /// Looks up a subcommand by name.
    fn subcommand_by_name<'a>(cmd: &'a Command, name: &str) -> Option<&'a Command> {
        cmd.subcommands
            .iter()
            .find(|s| s.name.as_deref() == Some(name))
    }

    // ── flyline --help (clap) ────────────────────────────────────────────────

    const FLYLINE_HELP: &str = r#"Usage: flyline [OPTIONS] [COMMAND]

Commands:
  set-agent-mode        Configure AI agent mode.
  create-prompt-widget  Create a custom prompt widget.
  set-style             Configure the colour palette.
  set-cursor            Configure the cursor appearance and animation.
  key                   Manage keybindings.
  dump-logs             Dump in-memory logs to file.
  stream-logs           Dump current logs to PATH and append new logs.
  run-tutorial          Run the interactive tutorial for first-time users.
  help                  Print this message or the help of the given subcommand(s)

Options:
      --version
          Show version information

      --log-level <LEVEL>
          Set the logging level
          
          [possible values: error, warn, info, debug, trace]

      --load-zsh-history [<PATH>]
          Load Zsh history in addition to Bash history. Optionally specify a PATH to the Zsh history file; if omitted, defaults to $HOME/.zsh_history

      --show-animations [<SHOW_ANIMATIONS>]
          Show animations
          
          [possible values: true, false]

      --show-inline-history [<SHOW_INLINE_HISTORY>]
          Show inline history suggestions
          
          [possible values: true, false]

      --auto-close-chars [<AUTO_CLOSE_CHARS>]
          Enable automatic closing character insertion (e.g. insert `)` after `(`)
          
          [possible values: true, false]

      --matrix-animation [<MATRIX_ANIMATION>]
          Run matrix animation in the terminal background. Use `on` to always show it, `off` to disable it, or an integer number of seconds to show it after that many seconds of inactivity (no keypress or mouse event). Defaults to `off`; passing the flag without a value is equivalent to `on`

      --set-frame-rate <FPS>
          Render frame rate in frames per second (1–120, default 24)

      --set-mouse-mode <MODE>
          Mouse capture mode (disabled, simple, smart). Default is smart.

      --send-shell-integration-codes [<SEND_SHELL_INTEGRATION_CODES>]
          Send shell integration escape codes (OSC 133 / OSC 633): none, only-prompt-pos, or full

      --enable-extended-key-codes [<ENABLE_EXTENDED_KEY_CODES>]
          Whether to request the use of extended (kitty-protocol) keyboard codes during startup. Enabled by default; pass `--enable-extended-key-codes false` (or with no value) to disable it on terminals that misbehave when the request is sent
          
          [possible values: true, false]

  -h, --help
          Print help (see a summary with '-h')

Read more at https://github.com/HalFrgrd/flyline
"#;

    #[test]
    fn test_flyline_help_clap() {
        let cmd = parse_help(FLYLINE_HELP);
        assert_eq!(cmd.name.as_deref(), Some("flyline"));

        // Subcommands and their descriptions.
        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"set-agent-mode"));
        assert!(subs.contains(&"create-prompt-widget"));
        assert!(subs.contains(&"set-style"));
        assert!(subs.contains(&"key"));
        assert!(subs.contains(&"dump-logs"));
        assert!(subs.contains(&"stream-logs"));
        assert!(subs.contains(&"run-tutorial"));
        assert_eq!(
            subcommand_by_name(&cmd, "set-agent-mode").and_then(|s| s.description.as_deref()),
            Some("Configure AI agent mode.")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "dump-logs").and_then(|s| s.description.as_deref()),
            Some("Dump in-memory logs to file.")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "stream-logs").and_then(|s| s.description.as_deref()),
            Some("Dump current logs to PATH and append new logs.")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "run-tutorial").and_then(|s| s.description.as_deref()),
            Some("Run the interactive tutorial for first-time users.")
        );

        // Flag names.
        let longs = long_names(&cmd);
        assert!(longs.contains(&"--version"));
        assert!(
            !longs.contains(&"--dump-logs"),
            "--dump-logs should be a subcommand now"
        );
        assert!(
            !longs.contains(&"--stream-logs"),
            "--stream-logs should be a subcommand now"
        );
        assert!(
            !longs.contains(&"--run-tutorial"),
            "--run-tutorial should be a subcommand now"
        );
        assert!(longs.contains(&"--log-level"));
        assert!(longs.contains(&"--set-frame-rate"));
        assert!(longs.contains(&"--set-mouse-mode"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        // Value types (meta-variable hints).
        assert_eq!(
            arg_by_long(&cmd, "--log-level").and_then(|a| a.value_type.as_deref()),
            Some("LEVEL")
        );
        assert_eq!(
            arg_by_long(&cmd, "--set-frame-rate").and_then(|a| a.value_type.as_deref()),
            Some("FPS")
        );
        assert_eq!(
            arg_by_long(&cmd, "--set-mouse-mode").and_then(|a| a.value_type.as_deref()),
            Some("MODE")
        );

        // Descriptions on continuation lines.
        assert_eq!(
            arg_by_long(&cmd, "--version").and_then(|a| a.description.as_deref()),
            Some("Show version information")
        );
        assert!(
            arg_by_long(&cmd, "--log-level")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("logging level"),
            "description should mention 'logging level'"
        );
    }

    // ── flyline create-anim --help (clap) ────────────────────────────────────
    const FLYLINE_CREATE_ANIM_HELP: &str = r#"Create a custom prompt animation.

Instances of NAME in prompt strings (PS1, RPS1, PS1_FILL) are replaced
with the current animation frame on every render.  Frames may include
ANSI colour sequences written as `\e` (e.g. `\e[33m`).

Examples:
  flyline create-anim --name "MY_ANIMATION" --fps 10  ⣾ ⣷ ⣯ ⣟ ⡿ ⢿ ⣻ ⣽
  flyline create-anim --name "john" --ping-pong --fps 5  '\e[33m\u' '\e[31m\u' '\e[35m\u' '\e[36m\u'

Usage: flyline create-anim [OPTIONS] --name <NAME> [FRAMES]...

Arguments:
  [FRAMES]...
          One or more animation frames (positional).  Use `\e` for the ESC character

Options:
      --name <NAME>
          Name to embed in prompt strings as the animation placeholder

      --fps <FPS>
          Playback speed in frames per second (default: 10)
          
          [default: 10]

      --ping-pong
          Reverse direction at each end instead of wrapping (ping-pong / bounce mode)

  -h, --help
          Print help (see a summary with '-h')
"#;

    #[test]
    fn test_flyline_create_anim_help_clap() {
        let cmd = parse_help(FLYLINE_CREATE_ANIM_HELP);
        assert_eq!(cmd.name.as_deref(), Some("flyline"));
        assert!(
            cmd.description
                .as_deref()
                .unwrap_or("")
                .contains("animation"),
            "description should mention animation"
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--name"));
        assert!(longs.contains(&"--fps"));
        assert!(longs.contains(&"--ping-pong"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        // Value types.
        assert_eq!(
            arg_by_long(&cmd, "--name").and_then(|a| a.value_type.as_deref()),
            Some("NAME")
        );
        assert_eq!(
            arg_by_long(&cmd, "--fps").and_then(|a| a.value_type.as_deref()),
            Some("FPS")
        );

        // Descriptions on continuation lines.
        assert!(
            arg_by_long(&cmd, "--name")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("animation placeholder"),
            "description should mention 'animation placeholder'"
        );
        assert!(
            arg_by_long(&cmd, "--fps")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("frames per second"),
            "description should mention 'frames per second'"
        );
        assert!(
            arg_by_long(&cmd, "--ping-pong")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("Reverse direction"),
            "description should mention 'Reverse direction'"
        );
    }

    // ── cargo --help (clap) ──────────────────────────────────────────────────

    const CARGO_HELP: &str = r#"Rust's package manager

Usage: cargo [+toolchain] [OPTIONS] [COMMAND]
       cargo [+toolchain] [OPTIONS] -Zscript [ARGS]...

Options:
  -V, --version              Print version info and exit
      --list                 List installed commands
      --explain <CODE>       Run `rustc --explain CODE`
  -v, --verbose              Use verbose output (-vv very verbose/build.rs output)
  -q, --quiet                Do not print cargo log messages
      --color <WHEN>         Coloring: auto, always, never
  -C <DIRECTORY>             Change to DIRECTORY before doing anything (nightly-only)
      --frozen               Require Cargo.lock and cache are up to date
      --locked               Require Cargo.lock is up to date
      --offline              Run without accessing the network
      --config <KEY=VALUE>   Override a configuration value
  -Z <FLAG>                  Unstable (nightly-only) flags to Cargo, see 'cargo -Z help' for details
  -h, --help                 Print help

Some common cargo commands are (see all commands with --list):
    build, b    Compile the current package
    check, c    Analyze the current package and report errors, but don't build object files
    clean       Remove the generated artifacts
    doc, d      Build this package's and its dependencies' documentation
    run, r      Run a binary or example of the local package
    test, t     Run the tests
    bench       Run the benchmarks
    update      Update dependencies listed in Cargo.lock
    search      Search registry for crates
    publish     Publish this package to the registry
    add         Add dependencies to a manifest file
    remove      Remove dependencies from a manifest file

See 'cargo help <command>' for more information on a specific command.
"#;

    #[test]
    fn test_cargo_help_clap() {
        let cmd = parse_help(CARGO_HELP);
        assert_eq!(cmd.name.as_deref(), Some("cargo"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--verbose"));
        assert!(longs.contains(&"--quiet"));
        assert!(longs.contains(&"--explain"));
        assert!(longs.contains(&"--color"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-V"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-h"));

        // Value types inferred from inline meta-variables.
        assert_eq!(
            arg_by_long(&cmd, "--explain").and_then(|a| a.value_type.as_deref()),
            Some("CODE")
        );
        assert_eq!(
            arg_by_long(&cmd, "--color").and_then(|a| a.value_type.as_deref()),
            Some("WHEN")
        );
    }

    // ── python --help (argparse-like, but actually custom) ───────────────────

    const PYTHON_HELP: &str = r#"usage: python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Options and arguments (and corresponding environment variables):
-b     : issue warnings about str(bytes_instance), str(bytearray_instance)
         and comparing bytes/bytearray with str. (-bb: issue errors)
-B     : don't write .pyc files on import; also PYTHONDONTWRITEBYTECODE=x
-c cmd : program passed in as string (terminates option list)
-d     : debug output from parser; also PYTHONDEBUG=x
-E     : ignore PYTHON* environment variables (such as PYTHONPATH)
-h     : print this help message and exit (also --help)
-i     : inspect interactively after running script; forces a prompt even
         if stdin does not appear to be a terminal; also PYTHONINSPECT=x
-I     : isolate Python from the user's environment (implies -E and -s)
-m mod : run library module as a script (terminates option list)
-O     : remove assert and __debug__-dependent statements; add .opt-1 before
         .pyc extension; also PYTHONOPTIMIZE=x
-OO    : do -O changes and also discard docstrings; add .opt-2 before
         .pyc extension
-q     : don't print version and copyright messages on interactive startup
-s     : don't add user site directory to sys.path; also PYTHONNOUSERSITE=x
-S     : don't imply 'import site' on initialization
-u     : force the stdout and stderr streams to be unbuffered;
         this option has no effect on stdin; also PYTHONASYNCIOGENIGNORE=x
-v     : verbose (trace import statements); also PYTHONVERBOSE=x;
         can be supplied multiple times to increase verbosity
-V     : print the Python version number and exit (also --version)
         --version :  print just the version number to stdout and exit
-W arg : warning control; arg is action:message:category:module:lineno
         also PYTHONWARNINGS=x
-x     : skip first line of source, allowing use of non-Unix forms of #!cmd
-X opt : set implementation-specific option
--check-hash-based-pycs always|default|never:
    control how Python invalidates hash-based .pyc files
file   : program read from script file
-      : program read from stdin (default; interactive mode if a tty)
arg ...: arguments passed to program in sys.argv[1:]

Other environment variables:
PYTHONSTARTUP: file executed on interactive startup (no default)
PYTHONPATH   : ':'-separated list of directories prefixed to the
               default module search path.  The result is sys.path.
"#;

    #[test]
    fn test_python_help_generic() {
        // python --help doesn't follow argparse or clap exactly; falls through to generic.
        let cmd = parse_help(PYTHON_HELP);
        assert_eq!(cmd.name.as_deref(), Some("python3"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-V"));
        assert!(shorts.contains(&"-q"));

        // Descriptions captured inline (separator is ` : `).
        assert!(
            cmd.args
                .iter()
                .find(|a| a.short.as_deref() == Some("-h"))
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("help message"),
            "description should mention 'help message'"
        );
    }

    // ── Python argparse example ───────────────────────────────────────────────

    const ARGPARSE_EXAMPLE: &str = r#"usage: prog.py [-h] [--foo FOO] bar

A sample argparse program.

positional arguments:
  bar          the bar argument

optional arguments:
  -h, --help   show this help message and exit
  --foo FOO    the foo value
"#;

    #[test]
    fn test_argparse_example() {
        let cmd = parse_help(ARGPARSE_EXAMPLE);
        assert_eq!(cmd.name.as_deref(), Some("prog.py"));
        assert!(
            cmd.description
                .as_deref()
                .unwrap_or("")
                .contains("argparse"),
            "description should mention argparse"
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"bar"));
        assert!(longs.contains(&"--foo"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        // Inline descriptions captured by the argparse parser.
        assert!(
            arg_by_long(&cmd, "bar")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("bar argument"),
            "description should mention 'bar argument'"
        );
        assert!(
            arg_by_long(&cmd, "--foo")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("foo value"),
            "description should mention 'foo value'"
        );
    }

    // ── Python argparse with subparsers ──────────────────────────────────────

    const ARGPARSE_SUBPARSERS: &str = r#"usage: myapp [-h] {init,run,stop} ...

My Application

positional arguments:
  {init,run,stop}
    init           Initialize the project
    run            Run the application
    stop           Stop the application

optional arguments:
  -h, --help       show this help message and exit
  --verbose        Enable verbose output
"#;

    #[test]
    fn test_argparse_subparsers() {
        let cmd = parse_help(ARGPARSE_SUBPARSERS);
        assert_eq!(cmd.name.as_deref(), Some("myapp"));
        assert!(
            cmd.description.as_deref().unwrap_or("").contains("My"),
            "description should mention 'My'"
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--verbose"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        // Inline description on --verbose.
        assert!(
            arg_by_long(&cmd, "--verbose")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("verbose output"),
            "description should mention 'verbose output'"
        );
    }

    // ── Click (Python) ────────────────────────────────────────────────────────

    const CLICK_HELP: &str = r#"Usage: cli [OPTIONS] COMMAND [ARGS]...

  A simple CLI built with Click.

Options:
  --name TEXT      The person to greet.
  --count INTEGER  Number of greetings.  [default: 1]
  -v, --verbose    Enable verbose output.
  --help           Show this message and exit.

Commands:
  hello    Greet someone.
  goodbye  Say goodbye.
"#;

    #[test]
    fn test_click_help() {
        let cmd = parse_help(CLICK_HELP);
        assert_eq!(cmd.name.as_deref(), Some("cli"));

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"hello"));
        assert!(subs.contains(&"goodbye"));

        // Subcommand descriptions.
        assert_eq!(
            subcommand_by_name(&cmd, "hello").and_then(|s| s.description.as_deref()),
            Some("Greet someone.")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "goodbye").and_then(|s| s.description.as_deref()),
            Some("Say goodbye.")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--name"));
        assert!(longs.contains(&"--count"));
        assert!(longs.contains(&"--verbose"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-v"));
    }

    // ── argh (Python) ─────────────────────────────────────────────────────────

    const ARGH_HELP: &str = r#"usage: myapp [-h] [--verbose] name

A program using argh.

positional arguments:
  name         the name argument

optional arguments:
  -h, --help   show this help message and exit
  --verbose    enable verbose output
"#;

    #[test]
    fn test_argh_help() {
        let cmd = parse_help(ARGH_HELP);
        assert_eq!(cmd.name.as_deref(), Some("myapp"));
        assert!(
            cmd.description.as_deref().unwrap_or("").contains("argh"),
            "description should mention argh"
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"name"));
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--verbose"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        // Inline descriptions from argparse format.
        assert!(
            arg_by_long(&cmd, "name")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("name argument"),
            "description should mention 'name argument'"
        );
        assert!(
            arg_by_long(&cmd, "--verbose")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("verbose output"),
            "description should mention 'verbose output'"
        );
    }

    // ── yargs (JavaScript) ────────────────────────────────────────────────────

    const YARGS_HELP: &str = r#"my-cli [options]

Commands:
  serve  Start the development server
  build  Build the project for production
  test   Run the test suite

Options:
      --help     Show help                 [boolean]
      --version  Show version number       [boolean]
  -p, --port     Port to listen on         [number]
"#;

    #[test]
    fn test_yargs_help() {
        let cmd = parse_help(YARGS_HELP);
        // No "Usage:" line in this yargs output; name is not extracted.
        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"serve"));
        assert!(subs.contains(&"build"));
        assert!(subs.contains(&"test"));

        // Subcommand descriptions.
        assert!(
            subcommand_by_name(&cmd, "serve")
                .and_then(|s| s.description.as_deref())
                .unwrap_or("")
                .contains("development server"),
            "description should mention 'development server'"
        );
        assert!(
            subcommand_by_name(&cmd, "build")
                .and_then(|s| s.description.as_deref())
                .unwrap_or("")
                .contains("production"),
            "description should mention 'production'"
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--port"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-p"));
    }

    // ── commander (JavaScript) ────────────────────────────────────────────────

    const COMMANDER_HELP: &str = r#"Usage: program [options] [command]

Options:
  -V, --version  output the version number
  -h, --help     display help for command

Commands:
  start          Start the server
  stop           Stop the server
  status         Show the server status
"#;

    #[test]
    fn test_commander_help() {
        let cmd = parse_help(COMMANDER_HELP);
        assert_eq!(cmd.name.as_deref(), Some("program"));

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"start"));
        assert!(subs.contains(&"stop"));
        assert!(subs.contains(&"status"));

        // Subcommand descriptions.
        assert_eq!(
            subcommand_by_name(&cmd, "start").and_then(|s| s.description.as_deref()),
            Some("Start the server")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "stop").and_then(|s| s.description.as_deref()),
            Some("Stop the server")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-V"));
        assert!(shorts.contains(&"-h"));
    }

    // ── cobra (Go) ────────────────────────────────────────────────────────────

    const COBRA_HELP: &str = r#"A brief description of your application.

Usage:
  myapp [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  serve       Start the server
  version     Print the version number

Flags:
  -h, --help     help for myapp
  -t, --toggle   Help message for toggle

Global Flags:
      --config string      config file (default "$HOME/.myapp.yaml")
      --log-level string   Log level (default "info")

Use "myapp [command] --help" for more information about a command.
"#;

    #[test]
    fn test_cobra_help() {
        let cmd = parse_help(COBRA_HELP);
        assert_eq!(cmd.name.as_deref(), Some("myapp"));
        assert!(
            cmd.description
                .as_deref()
                .unwrap_or("")
                .contains("application"),
            "description should mention application"
        );

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"serve"));
        assert!(subs.contains(&"version"));

        // Subcommand descriptions.
        assert_eq!(
            subcommand_by_name(&cmd, "serve").and_then(|s| s.description.as_deref()),
            Some("Start the server")
        );
        assert!(
            subcommand_by_name(&cmd, "completion")
                .and_then(|s| s.description.as_deref())
                .unwrap_or("")
                .contains("autocompletion"),
            "description should mention 'autocompletion'"
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--toggle"));
        assert!(longs.contains(&"--config"));
        assert!(longs.contains(&"--log-level"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));
        assert!(shorts.contains(&"-t"));
    }

    // ── docopt (Python) ───────────────────────────────────────────────────────

    const DOCOPT_HELP: &str = r#"Usage:
  naval_fate ship <name> move <x> <y> [--speed=<kn>]
  naval_fate ship shoot <x> <y>
  naval_fate mine (set|remove) <x> <y> [--moored|--drifting]
  naval_fate (-h | --help)
  naval_fate --version

Options:
  -h --help     Show this screen.
  --version     Show version.
  --speed=<kn>  Speed in knots [default: 10].
  --moored      Moored (anchored) mine.
  --drifting    Drifting mine.
"#;

    #[test]
    fn test_docopt_help() {
        let cmd = parse_help(DOCOPT_HELP);
        // Name extracted from the first usage pattern line.
        assert_eq!(cmd.name.as_deref(), Some("naval_fate"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--speed"));
        assert!(longs.contains(&"--moored"));
        assert!(longs.contains(&"--drifting"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        // --speed=<kn> carries a value-type hint.
        assert_eq!(
            arg_by_long(&cmd, "--speed").and_then(|a| a.value_type.as_deref()),
            Some("kn")
        );
    }

    // ── to_clap_command ───────────────────────────────────────────────────────

    #[test]
    fn test_to_clap_command_basic() {
        let cmd = Command {
            name: Some("mytool".to_string()),
            description: Some("A test tool.".to_string()),
            args: vec![
                Arg {
                    long: Some("--verbose".to_string()),
                    short: Some("-v".to_string()),
                    description: Some("Enable verbose output.".to_string()),
                    value_type: None,
                    num_args: None,
                },
                Arg {
                    long: Some("--output".to_string()),
                    short: None,
                    description: Some("Output file.".to_string()),
                    value_type: Some("<PATH>".to_string()),
                    num_args: None,
                },
            ],
            subcommands: vec![Command {
                name: Some("sub".to_string()),
                description: Some("A subcommand.".to_string()),
                args: vec![],
                subcommands: vec![],
                author: None,
            }],
            author: None,
        };

        let clap_cmd = to_clap_command(&cmd);

        assert_eq!(clap_cmd.get_name(), "mytool");

        // Check args are present.
        let arg_ids: Vec<&str> = clap_cmd
            .get_arguments()
            .map(|a| a.get_id().as_str())
            .collect();
        assert!(
            arg_ids.contains(&"verbose"),
            "verbose arg missing: {arg_ids:?}"
        );
        assert!(
            arg_ids.contains(&"output"),
            "output arg missing: {arg_ids:?}"
        );

        // Check subcommand is present.
        let sub_names: Vec<&str> = clap_cmd.get_subcommands().map(|s| s.get_name()).collect();
        assert!(
            sub_names.contains(&"sub"),
            "sub subcommand missing: {sub_names:?}"
        );
    }

    #[test]
    fn test_to_clap_command_generates_bash_completion() {
        // Parse a simple clap-style help and verify that the generated Bash
        // completion script is non-empty and references the command name.
        const HELP: &str = r#"Usage: greet [OPTIONS]

Options:
  -n, --name <NAME>  Name to greet
  -h, --help         Print help
"#;
        let cmd = parse_help(HELP);
        let mut clap_cmd = to_clap_command(&cmd);
        let bin_name = clap_cmd.get_name().to_string();
        let mut out = Vec::new();
        clap_complete::generate(
            clap_complete::Shell::Bash,
            &mut clap_cmd,
            &bin_name,
            &mut out,
        );
        let script = String::from_utf8(out).expect("completion output is valid utf-8");
        assert!(!script.is_empty());
        assert!(script.contains("greet"));
    }

    #[test]
    fn test_to_clap_command_drops_duplicate_short_flags() {
        let cmd = Command {
            name: Some("readelf".to_string()),
            description: Some("A test tool with duplicate short flags.".to_string()),
            args: vec![
                Arg {
                    long: Some("--debug-dump[a/".to_string()),
                    short: Some("-w".to_string()),
                    description: Some("DWARF debug dump selector.".to_string()),
                    value_type: None,
                    num_args: None,
                },
                Arg {
                    long: Some("--debug-dump".to_string()),
                    short: Some("-w".to_string()),
                    description: Some("DWARF debug dump mode.".to_string()),
                    value_type: Some("links".to_string()),
                    num_args: None,
                },
            ],
            subcommands: vec![],
            author: None,
        };

        let mut clap_cmd = to_clap_command(&cmd);
        let bin_name = clap_cmd.get_name().to_string();
        let mut out = Vec::new();
        clap_complete::generate(
            clap_complete::Shell::Bash,
            &mut clap_cmd,
            &bin_name,
            &mut out,
        );
        let script = String::from_utf8(out).expect("completion output is valid utf-8");
        assert!(!script.is_empty());
        assert!(script.contains("readelf"));
    }

    #[test]
    fn test_to_clap_command_drops_duplicate_long_flags() {
        let cmd = Command {
            name: Some("readelf".to_string()),
            description: Some("A test tool with duplicate long flags.".to_string()),
            args: vec![
                Arg {
                    long: Some("--debug-dump".to_string()),
                    short: Some("-w".to_string()),
                    description: Some("DWARF debug dump selector.".to_string()),
                    value_type: Some("a/".to_string()),
                    num_args: None,
                },
                Arg {
                    long: Some("--debug-dump".to_string()),
                    short: None,
                    description: Some("DWARF debug dump links mode.".to_string()),
                    value_type: Some("links".to_string()),
                    num_args: None,
                },
            ],
            subcommands: vec![],
            author: None,
        };

        let mut clap_cmd = to_clap_command(&cmd);
        let bin_name = clap_cmd.get_name().to_string();
        let mut out = Vec::new();
        clap_complete::generate(
            clap_complete::Shell::Bash,
            &mut clap_cmd,
            &bin_name,
            &mut out,
        );
        let script = String::from_utf8(out).expect("completion output is valid utf-8");
        assert!(!script.is_empty());
        assert!(script.contains("readelf"));
    }

    // ── git --help ───────────────────────────────────────────────────────────
    //
    // A simplified version of `git --help` using a standard Commands: section
    // so that the clap parser picks up the subcommands correctly.

    const GIT_HELP: &str = r#"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [--no-replace-objects] [--bare] [--git-dir=<path>] [--work-tree=<path>]
           <command> [<args>]

Usage: git [OPTIONS] <COMMAND>

Commands:
  clone     Clone a repository into a new directory
  init      Create an empty Git repository or reinitialize an existing one
  add       Add file contents to the index
  rm        Remove files from the working tree and from the index
  diff      Show changes between commits, commit and working tree, etc
  log       Show the commit logs
  status    Show the working tree status
  branch    List, create, or delete branches
  commit    Record changes to the repository
  merge     Join two or more development histories together
  rebase    Reapply commits on top of another base tip
  reset     Reset current HEAD to the specified state
  fetch     Download objects and refs from another repository
  pull      Fetch from and integrate with another repository or a local branch
  push      Update remote refs along with associated objects
  tag       Create, list, delete or verify a tag object signed with GPG

Options:
  -C <path>                Run as if git was started in <path>
  -c <name>=<value>        Pass a configuration parameter to the command
  -v, --version            Print the Git suite version
  -h, --help               Print help
"#;

    #[test]
    fn test_git_help() {
        let cmd = parse_help(GIT_HELP);
        assert_eq!(cmd.name.as_deref(), Some("git"));

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"clone"));
        assert!(subs.contains(&"commit"));
        assert!(subs.contains(&"log"));
        assert!(subs.contains(&"diff"));
        assert!(subs.contains(&"push"));
        assert!(subs.contains(&"pull"));
        assert!(subs.contains(&"branch"));
        assert!(subs.contains(&"status"));

        // Check a couple of subcommand descriptions.
        assert_eq!(
            subcommand_by_name(&cmd, "clone").and_then(|s| s.description.as_deref()),
            Some("Clone a repository into a new directory")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "commit").and_then(|s| s.description.as_deref()),
            Some("Record changes to the repository")
        );
    }

    // ── git log --help ────────────────────────────────────────────────────────

    const GIT_LOG_HELP: &str = r#"usage: git log [<options>] [<revision-range>] [[--] <path>...]

    -q, --quiet           Suppress diff output
    -v, --verbose         Be more verbose
    -n, --max-count <n>   Limit the number of commits to output
    --skip <n>            Skip number commits before starting to show output
    --since <date>        Show commits more recent than a specific date
    --after <date>        Show commits more recent than a specific date (alias)
    --until <date>        Show commits older than a specific date
    --before <date>       Show commits older than a specific date (alias)
    --author <pattern>    Limit output to commits with matching author
    --committer <pattern> Limit output to commits with matching committer
    --grep <pattern>      Limit commit output to ones matching the pattern
    --all-match           Limit output to commits matching all grep patterns
    -i, --regexp-ignore-case
                          Case insensitive match
    --oneline             Show one commit per line with abbreviated hash
    --no-walk             Only show given commits, not their parents
    --graph               Show the commit graph as ASCII art
    --decorate            Decorate refs
    --first-parent        Follow only the first parent commit upon merges
    -p, --patch           Show patch
    -s, --no-patch        Suppress diff output
    --stat                Generate a diffstat
    --format <format>     Pretty-print in given format
    --abbrev-commit       Show only a partial commit hash prefix
"#;

    #[test]
    fn test_git_log_help() {
        let cmd = parse_help(GIT_LOG_HELP);
        assert_eq!(cmd.name.as_deref(), Some("git"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-q"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-n"));
        assert!(shorts.contains(&"-p"));
        assert!(shorts.contains(&"-s"));
        assert!(shorts.contains(&"-i"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--max-count"));
        assert!(longs.contains(&"--since"));
        assert!(longs.contains(&"--author"));
        assert!(longs.contains(&"--grep"));
        assert!(longs.contains(&"--oneline"));
        assert!(longs.contains(&"--graph"));
        assert!(longs.contains(&"--stat"));
        assert!(longs.contains(&"--first-parent"));
        assert!(longs.contains(&"--patch"));
        assert!(longs.contains(&"--no-patch"));

        // Value types.
        assert_eq!(
            arg_by_long(&cmd, "--max-count").and_then(|a| a.value_type.as_deref()),
            Some("n")
        );
        assert_eq!(
            arg_by_long(&cmd, "--since").and_then(|a| a.value_type.as_deref()),
            Some("date")
        );
        assert_eq!(
            arg_by_long(&cmd, "--author").and_then(|a| a.value_type.as_deref()),
            Some("pattern")
        );

        // Descriptions.
        assert!(
            arg_by_long(&cmd, "--graph")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("ASCII"),
            "--graph description should mention ASCII"
        );
    }

    // ── git commit --help ────────────────────────────────────────────────────

    const GIT_COMMIT_HELP: &str = r#"usage: git commit [-a | --interactive | --patch] [-s] [-v] [--amend]
   [--author=<author>] [--date=<date>] [-m <msg>] [--no-verify]

    -q, --quiet           Suppress summary after successful commit
    -v, --verbose         Show diff in commit message template
    -F, --file <file>     Read message from file
    --author <author>     Override author for commit
    --date <date>         Override date for commit
    -m, --message <message>
                          Commit message
    -s, --signoff         Add a Signed-off-by trailer
    -e, --edit            Force edit of commit
    --cleanup <mode>      How to strip spaces and #comments from message
    --no-verify           Bypass pre-commit and commit-msg hooks
    --allow-empty         Allow recording an empty commit
    --allow-empty-message
                          Allow recording a commit with an empty message
    --amend               Amend previous commit
    -a, --all             Commit all changed files
    -i, --include         Add specified files to index for commit
    -o, --only            Commit only specified files
    --dry-run             Show what would be committed
    --short               Show status concisely
    --branch              Show branch information
    --squash <commit>     Use autosquash formatted message to squash specified commit
    --fixup <commit>      Use autosquash formatted message to fixup specified commit
"#;

    #[test]
    fn test_git_commit_help() {
        let cmd = parse_help(GIT_COMMIT_HELP);
        assert_eq!(cmd.name.as_deref(), Some("git"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-q"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-m"));
        assert!(shorts.contains(&"-a"));
        assert!(shorts.contains(&"-s"));
        assert!(shorts.contains(&"-e"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--message"));
        assert!(longs.contains(&"--author"));
        assert!(longs.contains(&"--amend"));
        assert!(longs.contains(&"--no-verify"));
        assert!(longs.contains(&"--allow-empty"));
        assert!(longs.contains(&"--dry-run"));
        assert!(longs.contains(&"--squash"));
        assert!(longs.contains(&"--signoff"));

        // Value types.
        assert_eq!(
            arg_by_long(&cmd, "--message").and_then(|a| a.value_type.as_deref()),
            Some("message")
        );
        assert_eq!(
            arg_by_long(&cmd, "--file").and_then(|a| a.value_type.as_deref()),
            Some("file")
        );
    }

    // ── git diff --help ───────────────────────────────────────────────────────

    const GIT_DIFF_HELP: &str = r#"usage: git diff [<options>] [<commit>] [--] [<path>...]
   or: git diff [<options>] --cached [<commit>] [--] [<path>...]
   or: git diff [<options>] <commit>...<commit> [--] [<path>...]

    -p, --patch           Show patch
    -s, --no-patch        Suppress diff output
    --raw                 Generate the diff in raw format
    --minimal             Produce the smallest possible diff
    --patience            Use the patience diff algorithm
    --histogram           Use the histogram diff algorithm
    --diff-algorithm <algorithm>
                          Choose a diff algorithm
    --stat                Generate a diffstat
    --compact-summary     Generate a compact summary in diffstat
    --numstat             Generate a diffstat in machine-readable form
    --shortstat           Output only the last line of --stat format
    --name-only           Show only names of changed files
    --name-status         Show only names and status of changed files
    --color <when>        Show colored diff (always, never, auto)
    --no-color            Turn off colored diff
    --word-diff <mode>    Show a word diff using the given mode
    -U, --unified <n>     Generate diffs with <n> lines of context
    --cached              View the changes staged for the next commit
    -W, --function-context
                          Show whole surrounding functions of changes
"#;

    #[test]
    fn test_git_diff_help() {
        let cmd = parse_help(GIT_DIFF_HELP);
        assert_eq!(cmd.name.as_deref(), Some("git"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-p"));
        assert!(shorts.contains(&"-s"));
        assert!(shorts.contains(&"-U"));
        assert!(shorts.contains(&"-W"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--patch"));
        assert!(longs.contains(&"--no-patch"));
        assert!(longs.contains(&"--stat"));
        assert!(longs.contains(&"--name-only"));
        assert!(longs.contains(&"--cached"));
        assert!(longs.contains(&"--word-diff"));
        assert!(longs.contains(&"--color"));
        assert!(longs.contains(&"--unified"));
    }

    // ── git with subcommand help synthesis (static test) ─────────────────────

    #[test]
    fn test_subcommand_synthesis_overlay() {
        let help_runner = |args: &[&str]| -> anyhow::Result<String> {
            let text = match args {
                [] => GIT_HELP,
                ["log"] => GIT_LOG_HELP,
                ["commit"] => GIT_COMMIT_HELP,
                ["diff"] => GIT_DIFF_HELP,
                _ => "",
            };
            Ok(text.to_string())
        };
        let top = synthesize_completion("git", help_runner).unwrap();

        assert!(subcommand_names(&top).contains(&"log"));
        assert!(subcommand_names(&top).contains(&"commit"));

        let log_sub = subcommand_by_name(&top, "log").expect("log subcommand should exist");
        assert!(long_names(log_sub).contains(&"--oneline"));
        assert!(long_names(log_sub).contains(&"--graph"));
        assert!(long_names(log_sub).contains(&"--since"));

        let commit_sub =
            subcommand_by_name(&top, "commit").expect("commit subcommand should exist");
        assert!(long_names(commit_sub).contains(&"--amend"));
        assert!(long_names(commit_sub).contains(&"--message"));
        assert!(long_names(commit_sub).contains(&"--no-verify"));

        let diff_sub = subcommand_by_name(&top, "diff").expect("diff subcommand should exist");
        assert!(long_names(diff_sub).contains(&"--cached"));
        assert!(long_names(diff_sub).contains(&"--stat"));
    }

    // ── find_subcommand_mut ───────────────────────────────────────────────────

    #[test]
    fn test_find_subcommand_mut_nested() {
        // Build a two-level tree: root → child → grandchild.
        let mut root = Command {
            name: Some("root".to_string()),
            description: None,
            args: vec![],
            subcommands: vec![Command {
                name: Some("child".to_string()),
                description: None,
                args: vec![],
                subcommands: vec![Command {
                    name: Some("grandchild".to_string()),
                    description: None,
                    args: vec![],
                    subcommands: vec![],
                    author: None,
                }],
                author: None,
            }],
            author: None,
        };

        // Navigate to grandchild via find_subcommand_mut.
        let path = vec!["child".to_string(), "grandchild".to_string()];
        let node = find_subcommand_mut(&mut root, &path).expect("grandchild should be found");
        assert_eq!(node.name.as_deref(), Some("grandchild"));

        // Populate it with an arg.
        node.args.push(Arg {
            long: Some("--verbose".to_string()),
            short: Some("-v".to_string()),
            description: Some("Be verbose".to_string()),
            value_type: None,
            num_args: None,
        });

        // Verify through the tree.
        let grandchild = root
            .subcommands
            .first()
            .and_then(|c| c.subcommands.first())
            .expect("grandchild should exist");
        assert_eq!(grandchild.args.len(), 1);
        assert_eq!(grandchild.args[0].long.as_deref(), Some("--verbose"));
    }

    #[test]
    fn test_find_subcommand_mut_missing() {
        let mut root = Command {
            name: Some("root".to_string()),
            description: None,
            args: vec![],
            subcommands: vec![],
            author: None,
        };
        // A path that doesn't exist should return None.
        let path = vec!["nonexistent".to_string()];
        assert!(find_subcommand_mut(&mut root, &path).is_none());
    }

    // ── Nested subcommand synthesis (static simulation) ───────────────────────
    //
    // Verify the stack-based iteration finds sub-sub-commands.  We simulate
    // a two-level subcommand tree (remote → add/set-url) and confirm that
    // args are populated at both levels.

    const GIT_REMOTE_HELP: &str = r#"Usage: git remote [OPTIONS] <COMMAND>

Commands:
  add      Add a remote
  set-url  Changes URLs for the remote
  remove   Remove a remote
  rename   Rename a remote

Options:
  -v, --verbose    Be verbose
  -h, --help       Print help
"#;

    const GIT_REMOTE_ADD_HELP: &str = r#"usage: git remote add <name> <url>

    -f, --fetch        Fetch after adding the remote
    -t, --track <branch>
                       Track given branch
    --tags             Import all tags
    --no-tags          Do not import tags
"#;

    const GIT_REMOTE_SET_URL_HELP: &str = r#"usage: git remote set-url [--push] <name> <new-url>

    --push             Manipulate push URLs
    --add              Add URL to list
    --delete           Delete URL
"#;

    const GIT_WITH_REMOTE_HELP: &str = r#"Usage: git [OPTIONS] <COMMAND>

Commands:
  clone   Clone a repository into a new directory
  remote  Manage set of tracked repositories

Options:
  -h, --help  Print help
"#;

    #[test]
    fn test_nested_subcommand_synthesis_simulation() {
        let help_runner = |args: &[&str]| -> anyhow::Result<String> {
            let text = match args {
                [] => GIT_WITH_REMOTE_HELP,
                ["remote"] => GIT_REMOTE_HELP,
                ["remote", "add"] => GIT_REMOTE_ADD_HELP,
                ["remote", "set-url"] => GIT_REMOTE_SET_URL_HELP,
                _ => "",
            };
            Ok(text.to_string())
        };
        let top = synthesize_completion("git", help_runner).unwrap();

        let remote =
            subcommand_by_name(&top, "remote").expect("remote subcommand should be present");
        assert!(long_names(remote).contains(&"--verbose"));

        let remote_add =
            subcommand_by_name(remote, "add").expect("remote add subcommand should be present");
        assert!(long_names(remote_add).contains(&"--fetch"));
        assert!(short_names(remote_add).contains(&"-f"));
        assert_eq!(
            arg_by_long(remote_add, "--track").and_then(|a| a.value_type.as_deref()),
            Some("branch")
        );

        let remote_set_url = subcommand_by_name(remote, "set-url")
            .expect("remote set-url subcommand should be present");
        assert!(long_names(remote_set_url).contains(&"--push"));
        assert!(long_names(remote_set_url).contains(&"--delete"));
    }

    // ── readelf --help ────────────────────────────────────────────────────────
    //
    // readelf uses a non-standard "Options are:" section header and inline
    // descriptions, making it a useful real-world test for the generic
    // section-header recognition and the inline-description capture paths.

    const READELF_HELP: &str = r#"Usage: readelf <option(s)> elf-file(s)
 Display information about the contents of ELF format files
 Options are:
  -a --all               Equivalent to: -h -l -S -s -r -d -V -A -I
  -h --file-header       Display the ELF file header
  -l --program-headers   Display the program headers
     --segments          An alias for --program-headers
  -S --section-headers   Display the sections' header
     --sections          An alias for --section-headers
  -g --section-groups    Display the section groups
  -t --section-details   Display the section details
  -e --headers           Equivalent to: -h -l -S
  -s --syms              Display the symbol table
     --symbols           An alias for --syms
     --dyn-syms          Display the dynamic symbol table
     --lto-syms          Display LTO symbol tables
     --sym-base=[0|8|10|16] 
                         Force base for symbol sizes.  The options are 
                         mixed (the default), octal, decimal, hexadecimal.
  -C --demangle[=STYLE]  Decode mangled/processed symbol names
                           STYLE can be "none", "auto", "gnu-v3", "java",
                           "gnat", "dlang", "rust"
     --no-demangle       Do not demangle low-level symbol names.  (default)
     --recurse-limit     Enable a demangling recursion limit.  (default)
     --no-recurse-limit  Disable a demangling recursion limit
  -n --notes             Display the contents of note sections (if present)
  -r --relocs            Display the relocations (if present)
  -u --unwind            Display the unwind info (if present)
  -d --dynamic           Display the dynamic section (if present)
  -V --version-info      Display the version sections (if present)
  -A --arch-specific     Display architecture specific information (if any)
  -c --archive-index     Display the symbol/file index in an archive
  -D --use-dynamic       Use the dynamic section info when displaying symbols
  -L --lint|--enable-checks
                         Display warning messages for possible problems
  -x --hex-dump=<number|name>
                         Dump the contents of section <number|name> as bytes
  -p --string-dump=<number|name>
                         Dump the contents of section <number|name> as strings
  -R --relocated-dump=<number|name>
                         Dump the relocated contents of section <number|name>
  -z --decompress        Decompress section before dumping it
  -I --histogram         Display histogram of bucket list lengths
  -W --wide              Allow output width to exceed 80 characters
  -T --silent-truncation If a symbol name is truncated, do not add [...] suffix
  -H --help              Display this information
  -v --version           Display the version number of readelf
Report bugs to <https://sourceware.org/bugzilla/>
"#;

    #[test]
    fn test_readelf_help() {
        let cmd = parse_help(READELF_HELP);
        assert_eq!(cmd.name.as_deref(), Some("readelf"));

        // Key short flags.
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-a"));
        assert!(shorts.contains(&"-h"));
        assert!(shorts.contains(&"-l"));
        assert!(shorts.contains(&"-S"));
        assert!(shorts.contains(&"-r"));
        assert!(shorts.contains(&"-d"));
        assert!(shorts.contains(&"-n"));
        assert!(shorts.contains(&"-W"));
        assert!(shorts.contains(&"-H"));
        assert!(shorts.contains(&"-v"));

        // Key long flags.
        let longs = long_names(&cmd);
        assert!(longs.contains(&"--all"));
        assert!(longs.contains(&"--file-header"));
        assert!(longs.contains(&"--program-headers"));
        assert!(longs.contains(&"--section-headers"));
        assert!(longs.contains(&"--relocs"));
        assert!(longs.contains(&"--dynamic"));
        assert!(longs.contains(&"--notes"));
        assert!(longs.contains(&"--wide"));
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--hex-dump"));

        // Value type extracted from --hex-dump=<number|name>.
        assert_eq!(
            arg_by_long(&cmd, "--hex-dump").and_then(|a| a.value_type.as_deref()),
            Some("number|name")
        );
    }

    #[test]
    fn test_parse_flag_tokens_ignores_multi_character_short_forms() {
        let (short, long, value_type) = parse_flag_tokens("-wk --debug-dump=links");
        assert_eq!(short, None);
        assert_eq!(long.as_deref(), Some("--debug-dump"));
        assert_eq!(value_type.as_deref(), Some("links"));

        let (short, long, value_type) =
            parse_flag_tokens("-U[dlexhi] --unicode=[default|locale|escape|hex|highlight|invalid]");
        assert_eq!(short, None);
        assert_eq!(long.as_deref(), Some("--unicode"));
        assert_eq!(
            value_type.as_deref(),
            Some("[default|locale|escape|hex|highlight|invalid]")
        );
    }
}
